# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AgentTestCaseResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'input': 'JSONValue',
        'output': 'JSONValue',
        'metadata': 'object'
    }

    attribute_map = {
        'id': 'id',
        'input': 'input',
        'output': 'output',
        'metadata': 'metadata'
    }

    def __init__(self, id=None, input=None, output=None, metadata=None):  # noqa: E501
        """AgentTestCaseResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._input = None
        self._output = None
        self._metadata = None
        self.discriminator = None
        self.id = id
        if input is not None:
            self.input = input
        if output is not None:
            self.output = output
        if metadata is not None:
            self.metadata = metadata

    @property
    def id(self):
        """Gets the id of this AgentTestCaseResponse.  # noqa: E501


        :return: The id of this AgentTestCaseResponse.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AgentTestCaseResponse.


        :param id: The id of this AgentTestCaseResponse.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def input(self):
        """Gets the input of this AgentTestCaseResponse.  # noqa: E501


        :return: The input of this AgentTestCaseResponse.  # noqa: E501
        :rtype: JSONValue
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this AgentTestCaseResponse.


        :param input: The input of this AgentTestCaseResponse.  # noqa: E501
        :type: JSONValue
        """

        self._input = input

    @property
    def output(self):
        """Gets the output of this AgentTestCaseResponse.  # noqa: E501


        :return: The output of this AgentTestCaseResponse.  # noqa: E501
        :rtype: JSONValue
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this AgentTestCaseResponse.


        :param output: The output of this AgentTestCaseResponse.  # noqa: E501
        :type: JSONValue
        """

        self._output = output

    @property
    def metadata(self):
        """Gets the metadata of this AgentTestCaseResponse.  # noqa: E501


        :return: The metadata of this AgentTestCaseResponse.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this AgentTestCaseResponse.


        :param metadata: The metadata of this AgentTestCaseResponse.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AgentTestCaseResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgentTestCaseResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
