# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnthropicBase64Source(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'object',
        'media_type': 'object',
        'type': 'object'
    }

    attribute_map = {
        'data': 'data',
        'media_type': 'media_type',
        'type': 'type'
    }

    def __init__(self, data=None, media_type=None, type=None):  # noqa: E501
        """AnthropicBase64Source - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._media_type = None
        self._type = None
        self.discriminator = None
        self.data = data
        self.media_type = media_type
        if type is not None:
            self.type = type

    @property
    def data(self):
        """Gets the data of this AnthropicBase64Source.  # noqa: E501


        :return: The data of this AnthropicBase64Source.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this AnthropicBase64Source.


        :param data: The data of this AnthropicBase64Source.  # noqa: E501
        :type: object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def media_type(self):
        """Gets the media_type of this AnthropicBase64Source.  # noqa: E501


        :return: The media_type of this AnthropicBase64Source.  # noqa: E501
        :rtype: object
        """
        return self._media_type

    @media_type.setter
    def media_type(self, media_type):
        """Sets the media_type of this AnthropicBase64Source.


        :param media_type: The media_type of this AnthropicBase64Source.  # noqa: E501
        :type: object
        """
        if media_type is None:
            raise ValueError("Invalid value for `media_type`, must not be `None`")  # noqa: E501

        self._media_type = media_type

    @property
    def type(self):
        """Gets the type of this AnthropicBase64Source.  # noqa: E501


        :return: The type of this AnthropicBase64Source.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AnthropicBase64Source.


        :param type: The type of this AnthropicBase64Source.  # noqa: E501
        :type: object
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnthropicBase64Source, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnthropicBase64Source):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
