# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BasicTestListInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'prompt_input_keys': 'object',
        'supports_history': 'object',
        'media_input_keys': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'prompt_input_keys': 'prompt_input_keys',
        'supports_history': 'supports_history',
        'media_input_keys': 'media_input_keys'
    }

    def __init__(self, id=None, name=None, prompt_input_keys=None, supports_history=None, media_input_keys=None):  # noqa: E501
        """BasicTestListInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._prompt_input_keys = None
        self._supports_history = None
        self._media_input_keys = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.prompt_input_keys = prompt_input_keys
        self.supports_history = supports_history
        if media_input_keys is not None:
            self.media_input_keys = media_input_keys

    @property
    def id(self):
        """Gets the id of this BasicTestListInfo.  # noqa: E501


        :return: The id of this BasicTestListInfo.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BasicTestListInfo.


        :param id: The id of this BasicTestListInfo.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this BasicTestListInfo.  # noqa: E501


        :return: The name of this BasicTestListInfo.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BasicTestListInfo.


        :param name: The name of this BasicTestListInfo.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def prompt_input_keys(self):
        """Gets the prompt_input_keys of this BasicTestListInfo.  # noqa: E501


        :return: The prompt_input_keys of this BasicTestListInfo.  # noqa: E501
        :rtype: object
        """
        return self._prompt_input_keys

    @prompt_input_keys.setter
    def prompt_input_keys(self, prompt_input_keys):
        """Sets the prompt_input_keys of this BasicTestListInfo.


        :param prompt_input_keys: The prompt_input_keys of this BasicTestListInfo.  # noqa: E501
        :type: object
        """
        if prompt_input_keys is None:
            raise ValueError("Invalid value for `prompt_input_keys`, must not be `None`")  # noqa: E501

        self._prompt_input_keys = prompt_input_keys

    @property
    def supports_history(self):
        """Gets the supports_history of this BasicTestListInfo.  # noqa: E501


        :return: The supports_history of this BasicTestListInfo.  # noqa: E501
        :rtype: object
        """
        return self._supports_history

    @supports_history.setter
    def supports_history(self, supports_history):
        """Sets the supports_history of this BasicTestListInfo.


        :param supports_history: The supports_history of this BasicTestListInfo.  # noqa: E501
        :type: object
        """
        if supports_history is None:
            raise ValueError("Invalid value for `supports_history`, must not be `None`")  # noqa: E501

        self._supports_history = supports_history

    @property
    def media_input_keys(self):
        """Gets the media_input_keys of this BasicTestListInfo.  # noqa: E501


        :return: The media_input_keys of this BasicTestListInfo.  # noqa: E501
        :rtype: object
        """
        return self._media_input_keys

    @media_input_keys.setter
    def media_input_keys(self, media_input_keys):
        """Sets the media_input_keys of this BasicTestListInfo.


        :param media_input_keys: The media_input_keys of this BasicTestListInfo.  # noqa: E501
        :type: object
        """

        self._media_input_keys = media_input_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BasicTestListInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BasicTestListInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
