# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompletionSummaryInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'session_id': 'object',
        'start_time': 'object',
        'end_time': 'object',
        'cost': 'object',
        'latency': 'object',
        'total_tokens': 'object',
        'prompt_name': 'object',
        'prompt_version_name': 'object',
        'model': 'object',
        'provider': 'object',
        'api_key_name': 'object',
        'environment': 'object',
        'has_human_evaluation': 'object',
        'has_auto_evaluation': 'object',
        'client_evaluations': 'object',
        'custom_metadata': 'object',
        'completion_feedback': 'object',
        'assignee': 'object',
        'prompt_template_config': 'object',
        'children': 'object',
        'kind': 'object',
        'review': 'object',
        'evaluations': 'object'
    }

    attribute_map = {
        'id': 'id',
        'session_id': 'session_id',
        'start_time': 'start_time',
        'end_time': 'end_time',
        'cost': 'cost',
        'latency': 'latency',
        'total_tokens': 'total_tokens',
        'prompt_name': 'prompt_name',
        'prompt_version_name': 'prompt_version_name',
        'model': 'model',
        'provider': 'provider',
        'api_key_name': 'api_key_name',
        'environment': 'environment',
        'has_human_evaluation': 'has_human_evaluation',
        'has_auto_evaluation': 'has_auto_evaluation',
        'client_evaluations': 'client_evaluations',
        'custom_metadata': 'custom_metadata',
        'completion_feedback': 'completion_feedback',
        'assignee': 'assignee',
        'prompt_template_config': 'prompt_template_config',
        'children': 'children',
        'kind': 'kind',
        'review': 'review',
        'evaluations': 'evaluations'
    }

    def __init__(self, id=None, session_id=None, start_time=None, end_time=None, cost=None, latency=None, total_tokens=None, prompt_name=None, prompt_version_name=None, model=None, provider=None, api_key_name=None, environment=None, has_human_evaluation=None, has_auto_evaluation=None, client_evaluations=None, custom_metadata=None, completion_feedback=None, assignee=None, prompt_template_config=None, children=None, kind=None, review=None, evaluations=None):  # noqa: E501
        """CompletionSummaryInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._session_id = None
        self._start_time = None
        self._end_time = None
        self._cost = None
        self._latency = None
        self._total_tokens = None
        self._prompt_name = None
        self._prompt_version_name = None
        self._model = None
        self._provider = None
        self._api_key_name = None
        self._environment = None
        self._has_human_evaluation = None
        self._has_auto_evaluation = None
        self._client_evaluations = None
        self._custom_metadata = None
        self._completion_feedback = None
        self._assignee = None
        self._prompt_template_config = None
        self._children = None
        self._kind = None
        self._review = None
        self._evaluations = None
        self.discriminator = None
        self.id = id
        self.session_id = session_id
        self.start_time = start_time
        self.end_time = end_time
        self.cost = cost
        self.latency = latency
        self.total_tokens = total_tokens
        self.prompt_name = prompt_name
        self.prompt_version_name = prompt_version_name
        self.model = model
        self.provider = provider
        self.api_key_name = api_key_name
        self.environment = environment
        self.has_human_evaluation = has_human_evaluation
        self.has_auto_evaluation = has_auto_evaluation
        self.client_evaluations = client_evaluations
        self.custom_metadata = custom_metadata
        self.completion_feedback = completion_feedback
        self.assignee = assignee
        self.prompt_template_config = prompt_template_config
        self.children = children
        if kind is not None:
            self.kind = kind
        if review is not None:
            self.review = review
        if evaluations is not None:
            self.evaluations = evaluations

    @property
    def id(self):
        """Gets the id of this CompletionSummaryInfo.  # noqa: E501


        :return: The id of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CompletionSummaryInfo.


        :param id: The id of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def session_id(self):
        """Gets the session_id of this CompletionSummaryInfo.  # noqa: E501


        :return: The session_id of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this CompletionSummaryInfo.


        :param session_id: The session_id of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def start_time(self):
        """Gets the start_time of this CompletionSummaryInfo.  # noqa: E501


        :return: The start_time of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this CompletionSummaryInfo.


        :param start_time: The start_time of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this CompletionSummaryInfo.  # noqa: E501


        :return: The end_time of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this CompletionSummaryInfo.


        :param end_time: The end_time of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    @property
    def cost(self):
        """Gets the cost of this CompletionSummaryInfo.  # noqa: E501


        :return: The cost of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """Sets the cost of this CompletionSummaryInfo.


        :param cost: The cost of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if cost is None:
            raise ValueError("Invalid value for `cost`, must not be `None`")  # noqa: E501

        self._cost = cost

    @property
    def latency(self):
        """Gets the latency of this CompletionSummaryInfo.  # noqa: E501


        :return: The latency of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._latency

    @latency.setter
    def latency(self, latency):
        """Sets the latency of this CompletionSummaryInfo.


        :param latency: The latency of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if latency is None:
            raise ValueError("Invalid value for `latency`, must not be `None`")  # noqa: E501

        self._latency = latency

    @property
    def total_tokens(self):
        """Gets the total_tokens of this CompletionSummaryInfo.  # noqa: E501


        :return: The total_tokens of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._total_tokens

    @total_tokens.setter
    def total_tokens(self, total_tokens):
        """Sets the total_tokens of this CompletionSummaryInfo.


        :param total_tokens: The total_tokens of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if total_tokens is None:
            raise ValueError("Invalid value for `total_tokens`, must not be `None`")  # noqa: E501

        self._total_tokens = total_tokens

    @property
    def prompt_name(self):
        """Gets the prompt_name of this CompletionSummaryInfo.  # noqa: E501


        :return: The prompt_name of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._prompt_name

    @prompt_name.setter
    def prompt_name(self, prompt_name):
        """Sets the prompt_name of this CompletionSummaryInfo.


        :param prompt_name: The prompt_name of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if prompt_name is None:
            raise ValueError("Invalid value for `prompt_name`, must not be `None`")  # noqa: E501

        self._prompt_name = prompt_name

    @property
    def prompt_version_name(self):
        """Gets the prompt_version_name of this CompletionSummaryInfo.  # noqa: E501


        :return: The prompt_version_name of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._prompt_version_name

    @prompt_version_name.setter
    def prompt_version_name(self, prompt_version_name):
        """Sets the prompt_version_name of this CompletionSummaryInfo.


        :param prompt_version_name: The prompt_version_name of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if prompt_version_name is None:
            raise ValueError("Invalid value for `prompt_version_name`, must not be `None`")  # noqa: E501

        self._prompt_version_name = prompt_version_name

    @property
    def model(self):
        """Gets the model of this CompletionSummaryInfo.  # noqa: E501


        :return: The model of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this CompletionSummaryInfo.


        :param model: The model of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if model is None:
            raise ValueError("Invalid value for `model`, must not be `None`")  # noqa: E501

        self._model = model

    @property
    def provider(self):
        """Gets the provider of this CompletionSummaryInfo.  # noqa: E501


        :return: The provider of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this CompletionSummaryInfo.


        :param provider: The provider of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if provider is None:
            raise ValueError("Invalid value for `provider`, must not be `None`")  # noqa: E501

        self._provider = provider

    @property
    def api_key_name(self):
        """Gets the api_key_name of this CompletionSummaryInfo.  # noqa: E501


        :return: The api_key_name of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._api_key_name

    @api_key_name.setter
    def api_key_name(self, api_key_name):
        """Sets the api_key_name of this CompletionSummaryInfo.


        :param api_key_name: The api_key_name of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if api_key_name is None:
            raise ValueError("Invalid value for `api_key_name`, must not be `None`")  # noqa: E501

        self._api_key_name = api_key_name

    @property
    def environment(self):
        """Gets the environment of this CompletionSummaryInfo.  # noqa: E501


        :return: The environment of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._environment

    @environment.setter
    def environment(self, environment):
        """Sets the environment of this CompletionSummaryInfo.


        :param environment: The environment of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if environment is None:
            raise ValueError("Invalid value for `environment`, must not be `None`")  # noqa: E501

        self._environment = environment

    @property
    def has_human_evaluation(self):
        """Gets the has_human_evaluation of this CompletionSummaryInfo.  # noqa: E501


        :return: The has_human_evaluation of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._has_human_evaluation

    @has_human_evaluation.setter
    def has_human_evaluation(self, has_human_evaluation):
        """Sets the has_human_evaluation of this CompletionSummaryInfo.


        :param has_human_evaluation: The has_human_evaluation of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if has_human_evaluation is None:
            raise ValueError("Invalid value for `has_human_evaluation`, must not be `None`")  # noqa: E501

        self._has_human_evaluation = has_human_evaluation

    @property
    def has_auto_evaluation(self):
        """Gets the has_auto_evaluation of this CompletionSummaryInfo.  # noqa: E501


        :return: The has_auto_evaluation of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._has_auto_evaluation

    @has_auto_evaluation.setter
    def has_auto_evaluation(self, has_auto_evaluation):
        """Sets the has_auto_evaluation of this CompletionSummaryInfo.


        :param has_auto_evaluation: The has_auto_evaluation of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if has_auto_evaluation is None:
            raise ValueError("Invalid value for `has_auto_evaluation`, must not be `None`")  # noqa: E501

        self._has_auto_evaluation = has_auto_evaluation

    @property
    def client_evaluations(self):
        """Gets the client_evaluations of this CompletionSummaryInfo.  # noqa: E501


        :return: The client_evaluations of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._client_evaluations

    @client_evaluations.setter
    def client_evaluations(self, client_evaluations):
        """Sets the client_evaluations of this CompletionSummaryInfo.


        :param client_evaluations: The client_evaluations of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if client_evaluations is None:
            raise ValueError("Invalid value for `client_evaluations`, must not be `None`")  # noqa: E501

        self._client_evaluations = client_evaluations

    @property
    def custom_metadata(self):
        """Gets the custom_metadata of this CompletionSummaryInfo.  # noqa: E501


        :return: The custom_metadata of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._custom_metadata

    @custom_metadata.setter
    def custom_metadata(self, custom_metadata):
        """Sets the custom_metadata of this CompletionSummaryInfo.


        :param custom_metadata: The custom_metadata of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if custom_metadata is None:
            raise ValueError("Invalid value for `custom_metadata`, must not be `None`")  # noqa: E501

        self._custom_metadata = custom_metadata

    @property
    def completion_feedback(self):
        """Gets the completion_feedback of this CompletionSummaryInfo.  # noqa: E501


        :return: The completion_feedback of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._completion_feedback

    @completion_feedback.setter
    def completion_feedback(self, completion_feedback):
        """Sets the completion_feedback of this CompletionSummaryInfo.


        :param completion_feedback: The completion_feedback of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if completion_feedback is None:
            raise ValueError("Invalid value for `completion_feedback`, must not be `None`")  # noqa: E501

        self._completion_feedback = completion_feedback

    @property
    def assignee(self):
        """Gets the assignee of this CompletionSummaryInfo.  # noqa: E501


        :return: The assignee of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._assignee

    @assignee.setter
    def assignee(self, assignee):
        """Sets the assignee of this CompletionSummaryInfo.


        :param assignee: The assignee of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if assignee is None:
            raise ValueError("Invalid value for `assignee`, must not be `None`")  # noqa: E501

        self._assignee = assignee

    @property
    def prompt_template_config(self):
        """Gets the prompt_template_config of this CompletionSummaryInfo.  # noqa: E501


        :return: The prompt_template_config of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._prompt_template_config

    @prompt_template_config.setter
    def prompt_template_config(self, prompt_template_config):
        """Sets the prompt_template_config of this CompletionSummaryInfo.


        :param prompt_template_config: The prompt_template_config of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if prompt_template_config is None:
            raise ValueError("Invalid value for `prompt_template_config`, must not be `None`")  # noqa: E501

        self._prompt_template_config = prompt_template_config

    @property
    def children(self):
        """Gets the children of this CompletionSummaryInfo.  # noqa: E501


        :return: The children of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this CompletionSummaryInfo.


        :param children: The children of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """
        if children is None:
            raise ValueError("Invalid value for `children`, must not be `None`")  # noqa: E501

        self._children = children

    @property
    def kind(self):
        """Gets the kind of this CompletionSummaryInfo.  # noqa: E501


        :return: The kind of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this CompletionSummaryInfo.


        :param kind: The kind of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """

        self._kind = kind

    @property
    def review(self):
        """Gets the review of this CompletionSummaryInfo.  # noqa: E501


        :return: The review of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._review

    @review.setter
    def review(self, review):
        """Sets the review of this CompletionSummaryInfo.


        :param review: The review of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """

        self._review = review

    @property
    def evaluations(self):
        """Gets the evaluations of this CompletionSummaryInfo.  # noqa: E501


        :return: The evaluations of this CompletionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._evaluations

    @evaluations.setter
    def evaluations(self, evaluations):
        """Sets the evaluations of this CompletionSummaryInfo.


        :param evaluations: The evaluations of this CompletionSummaryInfo.  # noqa: E501
        :type: object
        """

        self._evaluations = evaluations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompletionSummaryInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompletionSummaryInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
