# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompletionListWithCompletionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'examples': 'object',
        'total_example_count': 'object',
        'has_more_examples': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'examples': 'examples',
        'total_example_count': 'total_example_count',
        'has_more_examples': 'has_more_examples'
    }

    def __init__(self, id=None, name=None, examples=None, total_example_count=None, has_more_examples=None):  # noqa: E501
        """CompletionListWithCompletionInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._examples = None
        self._total_example_count = None
        self._has_more_examples = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.examples = examples
        self.total_example_count = total_example_count
        self.has_more_examples = has_more_examples

    @property
    def id(self):
        """Gets the id of this CompletionListWithCompletionInfo.  # noqa: E501


        :return: The id of this CompletionListWithCompletionInfo.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CompletionListWithCompletionInfo.


        :param id: The id of this CompletionListWithCompletionInfo.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this CompletionListWithCompletionInfo.  # noqa: E501


        :return: The name of this CompletionListWithCompletionInfo.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CompletionListWithCompletionInfo.


        :param name: The name of this CompletionListWithCompletionInfo.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def examples(self):
        """Gets the examples of this CompletionListWithCompletionInfo.  # noqa: E501


        :return: The examples of this CompletionListWithCompletionInfo.  # noqa: E501
        :rtype: object
        """
        return self._examples

    @examples.setter
    def examples(self, examples):
        """Sets the examples of this CompletionListWithCompletionInfo.


        :param examples: The examples of this CompletionListWithCompletionInfo.  # noqa: E501
        :type: object
        """
        if examples is None:
            raise ValueError("Invalid value for `examples`, must not be `None`")  # noqa: E501

        self._examples = examples

    @property
    def total_example_count(self):
        """Gets the total_example_count of this CompletionListWithCompletionInfo.  # noqa: E501


        :return: The total_example_count of this CompletionListWithCompletionInfo.  # noqa: E501
        :rtype: object
        """
        return self._total_example_count

    @total_example_count.setter
    def total_example_count(self, total_example_count):
        """Sets the total_example_count of this CompletionListWithCompletionInfo.


        :param total_example_count: The total_example_count of this CompletionListWithCompletionInfo.  # noqa: E501
        :type: object
        """
        if total_example_count is None:
            raise ValueError("Invalid value for `total_example_count`, must not be `None`")  # noqa: E501

        self._total_example_count = total_example_count

    @property
    def has_more_examples(self):
        """Gets the has_more_examples of this CompletionListWithCompletionInfo.  # noqa: E501


        :return: The has_more_examples of this CompletionListWithCompletionInfo.  # noqa: E501
        :rtype: object
        """
        return self._has_more_examples

    @has_more_examples.setter
    def has_more_examples(self, has_more_examples):
        """Sets the has_more_examples of this CompletionListWithCompletionInfo.


        :param has_more_examples: The has_more_examples of this CompletionListWithCompletionInfo.  # noqa: E501
        :type: object
        """
        if has_more_examples is None:
            raise ValueError("Invalid value for `has_more_examples`, must not be `None`")  # noqa: E501

        self._has_more_examples = has_more_examples

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompletionListWithCompletionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompletionListWithCompletionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
