# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateCriteriaVersionRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'target_type': 'EvalTargetType',
        'target_id': 'object',
        'llm_eval_enabled': 'object',
        'sample_rate': 'object',
        'model_id': 'object',
        'type': 'object',
        'question': 'object',
        'llm_question': 'object',
        'rubric': 'object',
        'multi_select_labels': 'object',
        'description': 'object',
        'categories': 'object',
        'auto_categorization_references': 'object',
        'auto_categorization_allow_multiple_categories': 'object',
        'create_criteria_if_missing': 'object',
        'criteria_id': 'object',
        'overwrite_latest_version': 'object',
        'generate_insights': 'object'
    }

    attribute_map = {
        'name': 'name',
        'target_type': 'target_type',
        'target_id': 'target_id',
        'llm_eval_enabled': 'llm_eval_enabled',
        'sample_rate': 'sample_rate',
        'model_id': 'model_id',
        'type': 'type',
        'question': 'question',
        'llm_question': 'llm_question',
        'rubric': 'rubric',
        'multi_select_labels': 'multi_select_labels',
        'description': 'description',
        'categories': 'categories',
        'auto_categorization_references': 'auto_categorization_references',
        'auto_categorization_allow_multiple_categories': 'auto_categorization_allow_multiple_categories',
        'create_criteria_if_missing': 'create_criteria_if_missing',
        'criteria_id': 'criteria_id',
        'overwrite_latest_version': 'overwrite_latest_version',
        'generate_insights': 'generate_insights'
    }

    def __init__(self, name=None, target_type=None, target_id=None, llm_eval_enabled=None, sample_rate=None, model_id=None, type=None, question=None, llm_question=None, rubric=None, multi_select_labels=None, description=None, categories=None, auto_categorization_references=None, auto_categorization_allow_multiple_categories=None, create_criteria_if_missing=None, criteria_id=None, overwrite_latest_version=None, generate_insights=None):  # noqa: E501
        """CreateCriteriaVersionRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._target_type = None
        self._target_id = None
        self._llm_eval_enabled = None
        self._sample_rate = None
        self._model_id = None
        self._type = None
        self._question = None
        self._llm_question = None
        self._rubric = None
        self._multi_select_labels = None
        self._description = None
        self._categories = None
        self._auto_categorization_references = None
        self._auto_categorization_allow_multiple_categories = None
        self._create_criteria_if_missing = None
        self._criteria_id = None
        self._overwrite_latest_version = None
        self._generate_insights = None
        self.discriminator = None
        self.name = name
        self.target_type = target_type
        self.target_id = target_id
        self.llm_eval_enabled = llm_eval_enabled
        if sample_rate is not None:
            self.sample_rate = sample_rate
        if model_id is not None:
            self.model_id = model_id
        if type is not None:
            self.type = type
        if question is not None:
            self.question = question
        if llm_question is not None:
            self.llm_question = llm_question
        if rubric is not None:
            self.rubric = rubric
        if multi_select_labels is not None:
            self.multi_select_labels = multi_select_labels
        if description is not None:
            self.description = description
        if categories is not None:
            self.categories = categories
        if auto_categorization_references is not None:
            self.auto_categorization_references = auto_categorization_references
        if auto_categorization_allow_multiple_categories is not None:
            self.auto_categorization_allow_multiple_categories = auto_categorization_allow_multiple_categories
        if create_criteria_if_missing is not None:
            self.create_criteria_if_missing = create_criteria_if_missing
        if criteria_id is not None:
            self.criteria_id = criteria_id
        if overwrite_latest_version is not None:
            self.overwrite_latest_version = overwrite_latest_version
        if generate_insights is not None:
            self.generate_insights = generate_insights

    @property
    def name(self):
        """Gets the name of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The name of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateCriteriaVersionRequest.


        :param name: The name of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def target_type(self):
        """Gets the target_type of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The target_type of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: EvalTargetType
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type):
        """Sets the target_type of this CreateCriteriaVersionRequest.


        :param target_type: The target_type of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: EvalTargetType
        """
        if target_type is None:
            raise ValueError("Invalid value for `target_type`, must not be `None`")  # noqa: E501

        self._target_type = target_type

    @property
    def target_id(self):
        """Gets the target_id of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The target_id of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """Sets the target_id of this CreateCriteriaVersionRequest.


        :param target_id: The target_id of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """
        if target_id is None:
            raise ValueError("Invalid value for `target_id`, must not be `None`")  # noqa: E501

        self._target_id = target_id

    @property
    def llm_eval_enabled(self):
        """Gets the llm_eval_enabled of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The llm_eval_enabled of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._llm_eval_enabled

    @llm_eval_enabled.setter
    def llm_eval_enabled(self, llm_eval_enabled):
        """Sets the llm_eval_enabled of this CreateCriteriaVersionRequest.


        :param llm_eval_enabled: The llm_eval_enabled of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """
        if llm_eval_enabled is None:
            raise ValueError("Invalid value for `llm_eval_enabled`, must not be `None`")  # noqa: E501

        self._llm_eval_enabled = llm_eval_enabled

    @property
    def sample_rate(self):
        """Gets the sample_rate of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The sample_rate of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._sample_rate

    @sample_rate.setter
    def sample_rate(self, sample_rate):
        """Sets the sample_rate of this CreateCriteriaVersionRequest.


        :param sample_rate: The sample_rate of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._sample_rate = sample_rate

    @property
    def model_id(self):
        """Gets the model_id of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The model_id of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """Sets the model_id of this CreateCriteriaVersionRequest.


        :param model_id: The model_id of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._model_id = model_id

    @property
    def type(self):
        """Gets the type of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The type of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CreateCriteriaVersionRequest.


        :param type: The type of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._type = type

    @property
    def question(self):
        """Gets the question of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The question of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._question

    @question.setter
    def question(self, question):
        """Sets the question of this CreateCriteriaVersionRequest.


        :param question: The question of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._question = question

    @property
    def llm_question(self):
        """Gets the llm_question of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The llm_question of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._llm_question

    @llm_question.setter
    def llm_question(self, llm_question):
        """Sets the llm_question of this CreateCriteriaVersionRequest.


        :param llm_question: The llm_question of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._llm_question = llm_question

    @property
    def rubric(self):
        """Gets the rubric of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The rubric of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._rubric

    @rubric.setter
    def rubric(self, rubric):
        """Sets the rubric of this CreateCriteriaVersionRequest.


        :param rubric: The rubric of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._rubric = rubric

    @property
    def multi_select_labels(self):
        """Gets the multi_select_labels of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The multi_select_labels of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._multi_select_labels

    @multi_select_labels.setter
    def multi_select_labels(self, multi_select_labels):
        """Sets the multi_select_labels of this CreateCriteriaVersionRequest.


        :param multi_select_labels: The multi_select_labels of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._multi_select_labels = multi_select_labels

    @property
    def description(self):
        """Gets the description of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The description of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateCriteriaVersionRequest.


        :param description: The description of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def categories(self):
        """Gets the categories of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The categories of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this CreateCriteriaVersionRequest.


        :param categories: The categories of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._categories = categories

    @property
    def auto_categorization_references(self):
        """Gets the auto_categorization_references of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The auto_categorization_references of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._auto_categorization_references

    @auto_categorization_references.setter
    def auto_categorization_references(self, auto_categorization_references):
        """Sets the auto_categorization_references of this CreateCriteriaVersionRequest.


        :param auto_categorization_references: The auto_categorization_references of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._auto_categorization_references = auto_categorization_references

    @property
    def auto_categorization_allow_multiple_categories(self):
        """Gets the auto_categorization_allow_multiple_categories of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The auto_categorization_allow_multiple_categories of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._auto_categorization_allow_multiple_categories

    @auto_categorization_allow_multiple_categories.setter
    def auto_categorization_allow_multiple_categories(self, auto_categorization_allow_multiple_categories):
        """Sets the auto_categorization_allow_multiple_categories of this CreateCriteriaVersionRequest.


        :param auto_categorization_allow_multiple_categories: The auto_categorization_allow_multiple_categories of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._auto_categorization_allow_multiple_categories = auto_categorization_allow_multiple_categories

    @property
    def create_criteria_if_missing(self):
        """Gets the create_criteria_if_missing of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The create_criteria_if_missing of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._create_criteria_if_missing

    @create_criteria_if_missing.setter
    def create_criteria_if_missing(self, create_criteria_if_missing):
        """Sets the create_criteria_if_missing of this CreateCriteriaVersionRequest.


        :param create_criteria_if_missing: The create_criteria_if_missing of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._create_criteria_if_missing = create_criteria_if_missing

    @property
    def criteria_id(self):
        """Gets the criteria_id of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The criteria_id of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._criteria_id

    @criteria_id.setter
    def criteria_id(self, criteria_id):
        """Sets the criteria_id of this CreateCriteriaVersionRequest.


        :param criteria_id: The criteria_id of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._criteria_id = criteria_id

    @property
    def overwrite_latest_version(self):
        """Gets the overwrite_latest_version of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The overwrite_latest_version of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._overwrite_latest_version

    @overwrite_latest_version.setter
    def overwrite_latest_version(self, overwrite_latest_version):
        """Sets the overwrite_latest_version of this CreateCriteriaVersionRequest.


        :param overwrite_latest_version: The overwrite_latest_version of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._overwrite_latest_version = overwrite_latest_version

    @property
    def generate_insights(self):
        """Gets the generate_insights of this CreateCriteriaVersionRequest.  # noqa: E501


        :return: The generate_insights of this CreateCriteriaVersionRequest.  # noqa: E501
        :rtype: object
        """
        return self._generate_insights

    @generate_insights.setter
    def generate_insights(self, generate_insights):
        """Sets the generate_insights of this CreateCriteriaVersionRequest.


        :param generate_insights: The generate_insights of this CreateCriteriaVersionRequest.  # noqa: E501
        :type: object
        """

        self._generate_insights = generate_insights

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateCriteriaVersionRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateCriteriaVersionRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
