# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateProjectRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'is_private': 'object',
        'id': 'object',
        'freeplay_spend_limit_usd': 'object',
        'data_retention_days': 'object',
        'enable_eval_insights': 'object',
        'enable_review_insights': 'object'
    }

    attribute_map = {
        'name': 'name',
        'is_private': 'is_private',
        'id': 'id',
        'freeplay_spend_limit_usd': 'freeplay_spend_limit_usd',
        'data_retention_days': 'data_retention_days',
        'enable_eval_insights': 'enable_eval_insights',
        'enable_review_insights': 'enable_review_insights'
    }

    def __init__(self, name=None, is_private=None, id=None, freeplay_spend_limit_usd=None, data_retention_days=None, enable_eval_insights=None, enable_review_insights=None):  # noqa: E501
        """CreateProjectRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._is_private = None
        self._id = None
        self._freeplay_spend_limit_usd = None
        self._data_retention_days = None
        self._enable_eval_insights = None
        self._enable_review_insights = None
        self.discriminator = None
        self.name = name
        if is_private is not None:
            self.is_private = is_private
        if id is not None:
            self.id = id
        if freeplay_spend_limit_usd is not None:
            self.freeplay_spend_limit_usd = freeplay_spend_limit_usd
        if data_retention_days is not None:
            self.data_retention_days = data_retention_days
        if enable_eval_insights is not None:
            self.enable_eval_insights = enable_eval_insights
        if enable_review_insights is not None:
            self.enable_review_insights = enable_review_insights

    @property
    def name(self):
        """Gets the name of this CreateProjectRequest.  # noqa: E501


        :return: The name of this CreateProjectRequest.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateProjectRequest.


        :param name: The name of this CreateProjectRequest.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def is_private(self):
        """Gets the is_private of this CreateProjectRequest.  # noqa: E501


        :return: The is_private of this CreateProjectRequest.  # noqa: E501
        :rtype: object
        """
        return self._is_private

    @is_private.setter
    def is_private(self, is_private):
        """Sets the is_private of this CreateProjectRequest.


        :param is_private: The is_private of this CreateProjectRequest.  # noqa: E501
        :type: object
        """

        self._is_private = is_private

    @property
    def id(self):
        """Gets the id of this CreateProjectRequest.  # noqa: E501


        :return: The id of this CreateProjectRequest.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CreateProjectRequest.


        :param id: The id of this CreateProjectRequest.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def freeplay_spend_limit_usd(self):
        """Gets the freeplay_spend_limit_usd of this CreateProjectRequest.  # noqa: E501


        :return: The freeplay_spend_limit_usd of this CreateProjectRequest.  # noqa: E501
        :rtype: object
        """
        return self._freeplay_spend_limit_usd

    @freeplay_spend_limit_usd.setter
    def freeplay_spend_limit_usd(self, freeplay_spend_limit_usd):
        """Sets the freeplay_spend_limit_usd of this CreateProjectRequest.


        :param freeplay_spend_limit_usd: The freeplay_spend_limit_usd of this CreateProjectRequest.  # noqa: E501
        :type: object
        """

        self._freeplay_spend_limit_usd = freeplay_spend_limit_usd

    @property
    def data_retention_days(self):
        """Gets the data_retention_days of this CreateProjectRequest.  # noqa: E501


        :return: The data_retention_days of this CreateProjectRequest.  # noqa: E501
        :rtype: object
        """
        return self._data_retention_days

    @data_retention_days.setter
    def data_retention_days(self, data_retention_days):
        """Sets the data_retention_days of this CreateProjectRequest.


        :param data_retention_days: The data_retention_days of this CreateProjectRequest.  # noqa: E501
        :type: object
        """

        self._data_retention_days = data_retention_days

    @property
    def enable_eval_insights(self):
        """Gets the enable_eval_insights of this CreateProjectRequest.  # noqa: E501


        :return: The enable_eval_insights of this CreateProjectRequest.  # noqa: E501
        :rtype: object
        """
        return self._enable_eval_insights

    @enable_eval_insights.setter
    def enable_eval_insights(self, enable_eval_insights):
        """Sets the enable_eval_insights of this CreateProjectRequest.


        :param enable_eval_insights: The enable_eval_insights of this CreateProjectRequest.  # noqa: E501
        :type: object
        """

        self._enable_eval_insights = enable_eval_insights

    @property
    def enable_review_insights(self):
        """Gets the enable_review_insights of this CreateProjectRequest.  # noqa: E501


        :return: The enable_review_insights of this CreateProjectRequest.  # noqa: E501
        :rtype: object
        """
        return self._enable_review_insights

    @enable_review_insights.setter
    def enable_review_insights(self, enable_review_insights):
        """Sets the enable_review_insights of this CreateProjectRequest.


        :param enable_review_insights: The enable_review_insights of this CreateProjectRequest.  # noqa: E501
        :type: object
        """

        self._enable_review_insights = enable_review_insights

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateProjectRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateProjectRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
