# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DataSourceCounts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'human_labels_count': 'object',
        'customer_feedback_count': 'object'
    }

    attribute_map = {
        'human_labels_count': 'human_labels_count',
        'customer_feedback_count': 'customer_feedback_count'
    }

    def __init__(self, human_labels_count=None, customer_feedback_count=None):  # noqa: E501
        """DataSourceCounts - a model defined in Swagger"""  # noqa: E501
        self._human_labels_count = None
        self._customer_feedback_count = None
        self.discriminator = None
        if human_labels_count is not None:
            self.human_labels_count = human_labels_count
        if customer_feedback_count is not None:
            self.customer_feedback_count = customer_feedback_count

    @property
    def human_labels_count(self):
        """Gets the human_labels_count of this DataSourceCounts.  # noqa: E501


        :return: The human_labels_count of this DataSourceCounts.  # noqa: E501
        :rtype: object
        """
        return self._human_labels_count

    @human_labels_count.setter
    def human_labels_count(self, human_labels_count):
        """Sets the human_labels_count of this DataSourceCounts.


        :param human_labels_count: The human_labels_count of this DataSourceCounts.  # noqa: E501
        :type: object
        """

        self._human_labels_count = human_labels_count

    @property
    def customer_feedback_count(self):
        """Gets the customer_feedback_count of this DataSourceCounts.  # noqa: E501


        :return: The customer_feedback_count of this DataSourceCounts.  # noqa: E501
        :rtype: object
        """
        return self._customer_feedback_count

    @customer_feedback_count.setter
    def customer_feedback_count(self, customer_feedback_count):
        """Sets the customer_feedback_count of this DataSourceCounts.


        :param customer_feedback_count: The customer_feedback_count of this DataSourceCounts.  # noqa: E501
        :type: object
        """

        self._customer_feedback_count = customer_feedback_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataSourceCounts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataSourceCounts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
