# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DetailedSessionInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_id': 'object',
        'start_time': 'object',
        'custom_metadata': 'object',
        'messages': 'object'
    }

    attribute_map = {
        'session_id': 'session_id',
        'start_time': 'start_time',
        'custom_metadata': 'custom_metadata',
        'messages': 'messages'
    }

    def __init__(self, session_id=None, start_time=None, custom_metadata=None, messages=None):  # noqa: E501
        """DetailedSessionInfo - a model defined in Swagger"""  # noqa: E501
        self._session_id = None
        self._start_time = None
        self._custom_metadata = None
        self._messages = None
        self.discriminator = None
        self.session_id = session_id
        self.start_time = start_time
        self.custom_metadata = custom_metadata
        self.messages = messages

    @property
    def session_id(self):
        """Gets the session_id of this DetailedSessionInfo.  # noqa: E501


        :return: The session_id of this DetailedSessionInfo.  # noqa: E501
        :rtype: object
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this DetailedSessionInfo.


        :param session_id: The session_id of this DetailedSessionInfo.  # noqa: E501
        :type: object
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def start_time(self):
        """Gets the start_time of this DetailedSessionInfo.  # noqa: E501


        :return: The start_time of this DetailedSessionInfo.  # noqa: E501
        :rtype: object
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this DetailedSessionInfo.


        :param start_time: The start_time of this DetailedSessionInfo.  # noqa: E501
        :type: object
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def custom_metadata(self):
        """Gets the custom_metadata of this DetailedSessionInfo.  # noqa: E501


        :return: The custom_metadata of this DetailedSessionInfo.  # noqa: E501
        :rtype: object
        """
        return self._custom_metadata

    @custom_metadata.setter
    def custom_metadata(self, custom_metadata):
        """Sets the custom_metadata of this DetailedSessionInfo.


        :param custom_metadata: The custom_metadata of this DetailedSessionInfo.  # noqa: E501
        :type: object
        """
        if custom_metadata is None:
            raise ValueError("Invalid value for `custom_metadata`, must not be `None`")  # noqa: E501

        self._custom_metadata = custom_metadata

    @property
    def messages(self):
        """Gets the messages of this DetailedSessionInfo.  # noqa: E501


        :return: The messages of this DetailedSessionInfo.  # noqa: E501
        :rtype: object
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this DetailedSessionInfo.


        :param messages: The messages of this DetailedSessionInfo.  # noqa: E501
        :type: object
        """
        if messages is None:
            raise ValueError("Invalid value for `messages`, must not be `None`")  # noqa: E501

        self._messages = messages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DetailedSessionInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetailedSessionInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
