# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DownloadedMediaReference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base64_data': 'object',
        'content_type': 'object',
        'media_type': 'object',
        'asset_id': 'object',
        'session_id': 'object',
        'test_case_id': 'object',
        'filename': 'object',
        'kind': 'object'
    }

    attribute_map = {
        'base64_data': 'base64Data',
        'content_type': 'contentType',
        'media_type': 'media_type',
        'asset_id': 'asset_id',
        'session_id': 'session_id',
        'test_case_id': 'test_case_id',
        'filename': 'filename',
        'kind': 'kind'
    }

    def __init__(self, base64_data=None, content_type=None, media_type=None, asset_id=None, session_id=None, test_case_id=None, filename=None, kind=None):  # noqa: E501
        """DownloadedMediaReference - a model defined in Swagger"""  # noqa: E501
        self._base64_data = None
        self._content_type = None
        self._media_type = None
        self._asset_id = None
        self._session_id = None
        self._test_case_id = None
        self._filename = None
        self._kind = None
        self.discriminator = None
        self.base64_data = base64_data
        self.content_type = content_type
        self.media_type = media_type
        if asset_id is not None:
            self.asset_id = asset_id
        if session_id is not None:
            self.session_id = session_id
        if test_case_id is not None:
            self.test_case_id = test_case_id
        if filename is not None:
            self.filename = filename
        if kind is not None:
            self.kind = kind

    @property
    def base64_data(self):
        """Gets the base64_data of this DownloadedMediaReference.  # noqa: E501


        :return: The base64_data of this DownloadedMediaReference.  # noqa: E501
        :rtype: object
        """
        return self._base64_data

    @base64_data.setter
    def base64_data(self, base64_data):
        """Sets the base64_data of this DownloadedMediaReference.


        :param base64_data: The base64_data of this DownloadedMediaReference.  # noqa: E501
        :type: object
        """
        if base64_data is None:
            raise ValueError("Invalid value for `base64_data`, must not be `None`")  # noqa: E501

        self._base64_data = base64_data

    @property
    def content_type(self):
        """Gets the content_type of this DownloadedMediaReference.  # noqa: E501


        :return: The content_type of this DownloadedMediaReference.  # noqa: E501
        :rtype: object
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this DownloadedMediaReference.


        :param content_type: The content_type of this DownloadedMediaReference.  # noqa: E501
        :type: object
        """
        if content_type is None:
            raise ValueError("Invalid value for `content_type`, must not be `None`")  # noqa: E501

        self._content_type = content_type

    @property
    def media_type(self):
        """Gets the media_type of this DownloadedMediaReference.  # noqa: E501


        :return: The media_type of this DownloadedMediaReference.  # noqa: E501
        :rtype: object
        """
        return self._media_type

    @media_type.setter
    def media_type(self, media_type):
        """Sets the media_type of this DownloadedMediaReference.


        :param media_type: The media_type of this DownloadedMediaReference.  # noqa: E501
        :type: object
        """
        if media_type is None:
            raise ValueError("Invalid value for `media_type`, must not be `None`")  # noqa: E501

        self._media_type = media_type

    @property
    def asset_id(self):
        """Gets the asset_id of this DownloadedMediaReference.  # noqa: E501


        :return: The asset_id of this DownloadedMediaReference.  # noqa: E501
        :rtype: object
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this DownloadedMediaReference.


        :param asset_id: The asset_id of this DownloadedMediaReference.  # noqa: E501
        :type: object
        """

        self._asset_id = asset_id

    @property
    def session_id(self):
        """Gets the session_id of this DownloadedMediaReference.  # noqa: E501


        :return: The session_id of this DownloadedMediaReference.  # noqa: E501
        :rtype: object
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this DownloadedMediaReference.


        :param session_id: The session_id of this DownloadedMediaReference.  # noqa: E501
        :type: object
        """

        self._session_id = session_id

    @property
    def test_case_id(self):
        """Gets the test_case_id of this DownloadedMediaReference.  # noqa: E501


        :return: The test_case_id of this DownloadedMediaReference.  # noqa: E501
        :rtype: object
        """
        return self._test_case_id

    @test_case_id.setter
    def test_case_id(self, test_case_id):
        """Sets the test_case_id of this DownloadedMediaReference.


        :param test_case_id: The test_case_id of this DownloadedMediaReference.  # noqa: E501
        :type: object
        """

        self._test_case_id = test_case_id

    @property
    def filename(self):
        """Gets the filename of this DownloadedMediaReference.  # noqa: E501


        :return: The filename of this DownloadedMediaReference.  # noqa: E501
        :rtype: object
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this DownloadedMediaReference.


        :param filename: The filename of this DownloadedMediaReference.  # noqa: E501
        :type: object
        """

        self._filename = filename

    @property
    def kind(self):
        """Gets the kind of this DownloadedMediaReference.  # noqa: E501


        :return: The kind of this DownloadedMediaReference.  # noqa: E501
        :rtype: object
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this DownloadedMediaReference.


        :param kind: The kind of this DownloadedMediaReference.  # noqa: E501
        :type: object
        """

        self._kind = kind

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DownloadedMediaReference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DownloadedMediaReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
