# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IndicesInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'object',
        'shards': 'ShardInfo',
        'docs': 'DocInfo',
        'store_size_bytes': 'object',
        'fielddata_memory_size_bytes': 'object',
        'query_cache_memory_size_bytes': 'object'
    }

    attribute_map = {
        'count': 'count',
        'shards': 'shards',
        'docs': 'docs',
        'store_size_bytes': 'store_size_bytes',
        'fielddata_memory_size_bytes': 'fielddata_memory_size_bytes',
        'query_cache_memory_size_bytes': 'query_cache_memory_size_bytes'
    }

    def __init__(self, count=None, shards=None, docs=None, store_size_bytes=None, fielddata_memory_size_bytes=None, query_cache_memory_size_bytes=None):  # noqa: E501
        """IndicesInfo - a model defined in Swagger"""  # noqa: E501
        self._count = None
        self._shards = None
        self._docs = None
        self._store_size_bytes = None
        self._fielddata_memory_size_bytes = None
        self._query_cache_memory_size_bytes = None
        self.discriminator = None
        self.count = count
        self.shards = shards
        self.docs = docs
        self.store_size_bytes = store_size_bytes
        self.fielddata_memory_size_bytes = fielddata_memory_size_bytes
        self.query_cache_memory_size_bytes = query_cache_memory_size_bytes

    @property
    def count(self):
        """Gets the count of this IndicesInfo.  # noqa: E501


        :return: The count of this IndicesInfo.  # noqa: E501
        :rtype: object
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this IndicesInfo.


        :param count: The count of this IndicesInfo.  # noqa: E501
        :type: object
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def shards(self):
        """Gets the shards of this IndicesInfo.  # noqa: E501


        :return: The shards of this IndicesInfo.  # noqa: E501
        :rtype: ShardInfo
        """
        return self._shards

    @shards.setter
    def shards(self, shards):
        """Sets the shards of this IndicesInfo.


        :param shards: The shards of this IndicesInfo.  # noqa: E501
        :type: ShardInfo
        """
        if shards is None:
            raise ValueError("Invalid value for `shards`, must not be `None`")  # noqa: E501

        self._shards = shards

    @property
    def docs(self):
        """Gets the docs of this IndicesInfo.  # noqa: E501


        :return: The docs of this IndicesInfo.  # noqa: E501
        :rtype: DocInfo
        """
        return self._docs

    @docs.setter
    def docs(self, docs):
        """Sets the docs of this IndicesInfo.


        :param docs: The docs of this IndicesInfo.  # noqa: E501
        :type: DocInfo
        """
        if docs is None:
            raise ValueError("Invalid value for `docs`, must not be `None`")  # noqa: E501

        self._docs = docs

    @property
    def store_size_bytes(self):
        """Gets the store_size_bytes of this IndicesInfo.  # noqa: E501


        :return: The store_size_bytes of this IndicesInfo.  # noqa: E501
        :rtype: object
        """
        return self._store_size_bytes

    @store_size_bytes.setter
    def store_size_bytes(self, store_size_bytes):
        """Sets the store_size_bytes of this IndicesInfo.


        :param store_size_bytes: The store_size_bytes of this IndicesInfo.  # noqa: E501
        :type: object
        """
        if store_size_bytes is None:
            raise ValueError("Invalid value for `store_size_bytes`, must not be `None`")  # noqa: E501

        self._store_size_bytes = store_size_bytes

    @property
    def fielddata_memory_size_bytes(self):
        """Gets the fielddata_memory_size_bytes of this IndicesInfo.  # noqa: E501


        :return: The fielddata_memory_size_bytes of this IndicesInfo.  # noqa: E501
        :rtype: object
        """
        return self._fielddata_memory_size_bytes

    @fielddata_memory_size_bytes.setter
    def fielddata_memory_size_bytes(self, fielddata_memory_size_bytes):
        """Sets the fielddata_memory_size_bytes of this IndicesInfo.


        :param fielddata_memory_size_bytes: The fielddata_memory_size_bytes of this IndicesInfo.  # noqa: E501
        :type: object
        """
        if fielddata_memory_size_bytes is None:
            raise ValueError("Invalid value for `fielddata_memory_size_bytes`, must not be `None`")  # noqa: E501

        self._fielddata_memory_size_bytes = fielddata_memory_size_bytes

    @property
    def query_cache_memory_size_bytes(self):
        """Gets the query_cache_memory_size_bytes of this IndicesInfo.  # noqa: E501


        :return: The query_cache_memory_size_bytes of this IndicesInfo.  # noqa: E501
        :rtype: object
        """
        return self._query_cache_memory_size_bytes

    @query_cache_memory_size_bytes.setter
    def query_cache_memory_size_bytes(self, query_cache_memory_size_bytes):
        """Sets the query_cache_memory_size_bytes of this IndicesInfo.


        :param query_cache_memory_size_bytes: The query_cache_memory_size_bytes of this IndicesInfo.  # noqa: E501
        :type: object
        """
        if query_cache_memory_size_bytes is None:
            raise ValueError("Invalid value for `query_cache_memory_size_bytes`, must not be `None`")  # noqa: E501

        self._query_cache_memory_size_bytes = query_cache_memory_size_bytes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IndicesInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndicesInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
