# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobProgress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'step': 'object',
        'total_steps': 'object',
        'step_name': 'object'
    }

    attribute_map = {
        'step': 'step',
        'total_steps': 'total_steps',
        'step_name': 'step_name'
    }

    def __init__(self, step=None, total_steps=None, step_name=None):  # noqa: E501
        """JobProgress - a model defined in Swagger"""  # noqa: E501
        self._step = None
        self._total_steps = None
        self._step_name = None
        self.discriminator = None
        self.step = step
        self.total_steps = total_steps
        self.step_name = step_name

    @property
    def step(self):
        """Gets the step of this JobProgress.  # noqa: E501


        :return: The step of this JobProgress.  # noqa: E501
        :rtype: object
        """
        return self._step

    @step.setter
    def step(self, step):
        """Sets the step of this JobProgress.


        :param step: The step of this JobProgress.  # noqa: E501
        :type: object
        """
        if step is None:
            raise ValueError("Invalid value for `step`, must not be `None`")  # noqa: E501

        self._step = step

    @property
    def total_steps(self):
        """Gets the total_steps of this JobProgress.  # noqa: E501


        :return: The total_steps of this JobProgress.  # noqa: E501
        :rtype: object
        """
        return self._total_steps

    @total_steps.setter
    def total_steps(self, total_steps):
        """Sets the total_steps of this JobProgress.


        :param total_steps: The total_steps of this JobProgress.  # noqa: E501
        :type: object
        """
        if total_steps is None:
            raise ValueError("Invalid value for `total_steps`, must not be `None`")  # noqa: E501

        self._total_steps = total_steps

    @property
    def step_name(self):
        """Gets the step_name of this JobProgress.  # noqa: E501


        :return: The step_name of this JobProgress.  # noqa: E501
        :rtype: object
        """
        return self._step_name

    @step_name.setter
    def step_name(self, step_name):
        """Sets the step_name of this JobProgress.


        :param step_name: The step_name of this JobProgress.  # noqa: E501
        :type: object
        """
        if step_name is None:
            raise ValueError("Invalid value for `step_name`, must not be `None`")  # noqa: E501

        self._step_name = step_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobProgress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobProgress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
