# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MetricsByPromptAndAgent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'by_prompt': 'object',
        'by_agent': 'object'
    }

    attribute_map = {
        'by_prompt': 'by_prompt',
        'by_agent': 'by_agent'
    }

    def __init__(self, by_prompt=None, by_agent=None):  # noqa: E501
        """MetricsByPromptAndAgent - a model defined in Swagger"""  # noqa: E501
        self._by_prompt = None
        self._by_agent = None
        self.discriminator = None
        self.by_prompt = by_prompt
        self.by_agent = by_agent

    @property
    def by_prompt(self):
        """Gets the by_prompt of this MetricsByPromptAndAgent.  # noqa: E501


        :return: The by_prompt of this MetricsByPromptAndAgent.  # noqa: E501
        :rtype: object
        """
        return self._by_prompt

    @by_prompt.setter
    def by_prompt(self, by_prompt):
        """Sets the by_prompt of this MetricsByPromptAndAgent.


        :param by_prompt: The by_prompt of this MetricsByPromptAndAgent.  # noqa: E501
        :type: object
        """
        if by_prompt is None:
            raise ValueError("Invalid value for `by_prompt`, must not be `None`")  # noqa: E501

        self._by_prompt = by_prompt

    @property
    def by_agent(self):
        """Gets the by_agent of this MetricsByPromptAndAgent.  # noqa: E501


        :return: The by_agent of this MetricsByPromptAndAgent.  # noqa: E501
        :rtype: object
        """
        return self._by_agent

    @by_agent.setter
    def by_agent(self, by_agent):
        """Sets the by_agent of this MetricsByPromptAndAgent.


        :param by_agent: The by_agent of this MetricsByPromptAndAgent.  # noqa: E501
        :type: object
        """
        if by_agent is None:
            raise ValueError("Invalid value for `by_agent`, must not be `None`")  # noqa: E501

        self._by_agent = by_agent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MetricsByPromptAndAgent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetricsByPromptAndAgent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
