# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PaginationInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'page': 'object',
        'page_size': 'object',
        'has_next': 'object'
    }

    attribute_map = {
        'page': 'page',
        'page_size': 'page_size',
        'has_next': 'has_next'
    }

    def __init__(self, page=None, page_size=None, has_next=None):  # noqa: E501
        """PaginationInfo - a model defined in Swagger"""  # noqa: E501
        self._page = None
        self._page_size = None
        self._has_next = None
        self.discriminator = None
        self.page = page
        self.page_size = page_size
        self.has_next = has_next

    @property
    def page(self):
        """Gets the page of this PaginationInfo.  # noqa: E501


        :return: The page of this PaginationInfo.  # noqa: E501
        :rtype: object
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this PaginationInfo.


        :param page: The page of this PaginationInfo.  # noqa: E501
        :type: object
        """
        if page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501

        self._page = page

    @property
    def page_size(self):
        """Gets the page_size of this PaginationInfo.  # noqa: E501


        :return: The page_size of this PaginationInfo.  # noqa: E501
        :rtype: object
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this PaginationInfo.


        :param page_size: The page_size of this PaginationInfo.  # noqa: E501
        :type: object
        """
        if page_size is None:
            raise ValueError("Invalid value for `page_size`, must not be `None`")  # noqa: E501

        self._page_size = page_size

    @property
    def has_next(self):
        """Gets the has_next of this PaginationInfo.  # noqa: E501


        :return: The has_next of this PaginationInfo.  # noqa: E501
        :rtype: object
        """
        return self._has_next

    @has_next.setter
    def has_next(self, has_next):
        """Sets the has_next of this PaginationInfo.


        :param has_next: The has_next of this PaginationInfo.  # noqa: E501
        :type: object
        """
        if has_next is None:
            raise ValueError("Invalid value for `has_next`, must not be `None`")  # noqa: E501

        self._has_next = has_next

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaginationInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaginationInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
