# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectStats(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'completions': 'TotalCountWithGrowthPercentage',
        'test_cases': 'TotalCountWithDelta',
        'test_runs': 'TotalCountWithDelta',
        'prompt_template_versions': 'TotalCountWithDelta'
    }

    attribute_map = {
        'completions': 'completions',
        'test_cases': 'test_cases',
        'test_runs': 'test_runs',
        'prompt_template_versions': 'prompt_template_versions'
    }

    def __init__(self, completions=None, test_cases=None, test_runs=None, prompt_template_versions=None):  # noqa: E501
        """ProjectStats - a model defined in Swagger"""  # noqa: E501
        self._completions = None
        self._test_cases = None
        self._test_runs = None
        self._prompt_template_versions = None
        self.discriminator = None
        self.completions = completions
        self.test_cases = test_cases
        self.test_runs = test_runs
        self.prompt_template_versions = prompt_template_versions

    @property
    def completions(self):
        """Gets the completions of this ProjectStats.  # noqa: E501


        :return: The completions of this ProjectStats.  # noqa: E501
        :rtype: TotalCountWithGrowthPercentage
        """
        return self._completions

    @completions.setter
    def completions(self, completions):
        """Sets the completions of this ProjectStats.


        :param completions: The completions of this ProjectStats.  # noqa: E501
        :type: TotalCountWithGrowthPercentage
        """
        if completions is None:
            raise ValueError("Invalid value for `completions`, must not be `None`")  # noqa: E501

        self._completions = completions

    @property
    def test_cases(self):
        """Gets the test_cases of this ProjectStats.  # noqa: E501


        :return: The test_cases of this ProjectStats.  # noqa: E501
        :rtype: TotalCountWithDelta
        """
        return self._test_cases

    @test_cases.setter
    def test_cases(self, test_cases):
        """Sets the test_cases of this ProjectStats.


        :param test_cases: The test_cases of this ProjectStats.  # noqa: E501
        :type: TotalCountWithDelta
        """
        if test_cases is None:
            raise ValueError("Invalid value for `test_cases`, must not be `None`")  # noqa: E501

        self._test_cases = test_cases

    @property
    def test_runs(self):
        """Gets the test_runs of this ProjectStats.  # noqa: E501


        :return: The test_runs of this ProjectStats.  # noqa: E501
        :rtype: TotalCountWithDelta
        """
        return self._test_runs

    @test_runs.setter
    def test_runs(self, test_runs):
        """Sets the test_runs of this ProjectStats.


        :param test_runs: The test_runs of this ProjectStats.  # noqa: E501
        :type: TotalCountWithDelta
        """
        if test_runs is None:
            raise ValueError("Invalid value for `test_runs`, must not be `None`")  # noqa: E501

        self._test_runs = test_runs

    @property
    def prompt_template_versions(self):
        """Gets the prompt_template_versions of this ProjectStats.  # noqa: E501


        :return: The prompt_template_versions of this ProjectStats.  # noqa: E501
        :rtype: TotalCountWithDelta
        """
        return self._prompt_template_versions

    @prompt_template_versions.setter
    def prompt_template_versions(self, prompt_template_versions):
        """Sets the prompt_template_versions of this ProjectStats.


        :param prompt_template_versions: The prompt_template_versions of this ProjectStats.  # noqa: E501
        :type: TotalCountWithDelta
        """
        if prompt_template_versions is None:
            raise ValueError("Invalid value for `prompt_template_versions`, must not be `None`")  # noqa: E501

        self._prompt_template_versions = prompt_template_versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectStats, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectStats):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
