# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PromptOptimizationJobStatusResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'job_id': 'object',
        'status': 'object',
        'prompt_template_id': 'object',
        'original_version_id': 'object',
        'run_test_after_optimization': 'object',
        'created_at': 'object',
        'optimized_version_id': 'object',
        'test_run_id': 'object',
        'comparison_id': 'object',
        'changes_summary': 'object',
        'error_message': 'object',
        'data_sources_used': 'object',
        'completed_at': 'object',
        'progress': 'object'
    }

    attribute_map = {
        'job_id': 'job_id',
        'status': 'status',
        'prompt_template_id': 'prompt_template_id',
        'original_version_id': 'original_version_id',
        'run_test_after_optimization': 'run_test_after_optimization',
        'created_at': 'created_at',
        'optimized_version_id': 'optimized_version_id',
        'test_run_id': 'test_run_id',
        'comparison_id': 'comparison_id',
        'changes_summary': 'changes_summary',
        'error_message': 'error_message',
        'data_sources_used': 'data_sources_used',
        'completed_at': 'completed_at',
        'progress': 'progress'
    }

    def __init__(self, job_id=None, status=None, prompt_template_id=None, original_version_id=None, run_test_after_optimization=None, created_at=None, optimized_version_id=None, test_run_id=None, comparison_id=None, changes_summary=None, error_message=None, data_sources_used=None, completed_at=None, progress=None):  # noqa: E501
        """PromptOptimizationJobStatusResponse - a model defined in Swagger"""  # noqa: E501
        self._job_id = None
        self._status = None
        self._prompt_template_id = None
        self._original_version_id = None
        self._run_test_after_optimization = None
        self._created_at = None
        self._optimized_version_id = None
        self._test_run_id = None
        self._comparison_id = None
        self._changes_summary = None
        self._error_message = None
        self._data_sources_used = None
        self._completed_at = None
        self._progress = None
        self.discriminator = None
        self.job_id = job_id
        self.status = status
        self.prompt_template_id = prompt_template_id
        self.original_version_id = original_version_id
        self.run_test_after_optimization = run_test_after_optimization
        self.created_at = created_at
        if optimized_version_id is not None:
            self.optimized_version_id = optimized_version_id
        if test_run_id is not None:
            self.test_run_id = test_run_id
        if comparison_id is not None:
            self.comparison_id = comparison_id
        if changes_summary is not None:
            self.changes_summary = changes_summary
        if error_message is not None:
            self.error_message = error_message
        if data_sources_used is not None:
            self.data_sources_used = data_sources_used
        if completed_at is not None:
            self.completed_at = completed_at
        if progress is not None:
            self.progress = progress

    @property
    def job_id(self):
        """Gets the job_id of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The job_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this PromptOptimizationJobStatusResponse.


        :param job_id: The job_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """
        if job_id is None:
            raise ValueError("Invalid value for `job_id`, must not be `None`")  # noqa: E501

        self._job_id = job_id

    @property
    def status(self):
        """Gets the status of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The status of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PromptOptimizationJobStatusResponse.


        :param status: The status of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def prompt_template_id(self):
        """Gets the prompt_template_id of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The prompt_template_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._prompt_template_id

    @prompt_template_id.setter
    def prompt_template_id(self, prompt_template_id):
        """Sets the prompt_template_id of this PromptOptimizationJobStatusResponse.


        :param prompt_template_id: The prompt_template_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """
        if prompt_template_id is None:
            raise ValueError("Invalid value for `prompt_template_id`, must not be `None`")  # noqa: E501

        self._prompt_template_id = prompt_template_id

    @property
    def original_version_id(self):
        """Gets the original_version_id of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The original_version_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._original_version_id

    @original_version_id.setter
    def original_version_id(self, original_version_id):
        """Sets the original_version_id of this PromptOptimizationJobStatusResponse.


        :param original_version_id: The original_version_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """
        if original_version_id is None:
            raise ValueError("Invalid value for `original_version_id`, must not be `None`")  # noqa: E501

        self._original_version_id = original_version_id

    @property
    def run_test_after_optimization(self):
        """Gets the run_test_after_optimization of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The run_test_after_optimization of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._run_test_after_optimization

    @run_test_after_optimization.setter
    def run_test_after_optimization(self, run_test_after_optimization):
        """Sets the run_test_after_optimization of this PromptOptimizationJobStatusResponse.


        :param run_test_after_optimization: The run_test_after_optimization of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """
        if run_test_after_optimization is None:
            raise ValueError("Invalid value for `run_test_after_optimization`, must not be `None`")  # noqa: E501

        self._run_test_after_optimization = run_test_after_optimization

    @property
    def created_at(self):
        """Gets the created_at of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The created_at of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this PromptOptimizationJobStatusResponse.


        :param created_at: The created_at of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def optimized_version_id(self):
        """Gets the optimized_version_id of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The optimized_version_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._optimized_version_id

    @optimized_version_id.setter
    def optimized_version_id(self, optimized_version_id):
        """Sets the optimized_version_id of this PromptOptimizationJobStatusResponse.


        :param optimized_version_id: The optimized_version_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """

        self._optimized_version_id = optimized_version_id

    @property
    def test_run_id(self):
        """Gets the test_run_id of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The test_run_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._test_run_id

    @test_run_id.setter
    def test_run_id(self, test_run_id):
        """Sets the test_run_id of this PromptOptimizationJobStatusResponse.


        :param test_run_id: The test_run_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """

        self._test_run_id = test_run_id

    @property
    def comparison_id(self):
        """Gets the comparison_id of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The comparison_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._comparison_id

    @comparison_id.setter
    def comparison_id(self, comparison_id):
        """Sets the comparison_id of this PromptOptimizationJobStatusResponse.


        :param comparison_id: The comparison_id of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """

        self._comparison_id = comparison_id

    @property
    def changes_summary(self):
        """Gets the changes_summary of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The changes_summary of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._changes_summary

    @changes_summary.setter
    def changes_summary(self, changes_summary):
        """Sets the changes_summary of this PromptOptimizationJobStatusResponse.


        :param changes_summary: The changes_summary of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """

        self._changes_summary = changes_summary

    @property
    def error_message(self):
        """Gets the error_message of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The error_message of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this PromptOptimizationJobStatusResponse.


        :param error_message: The error_message of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """

        self._error_message = error_message

    @property
    def data_sources_used(self):
        """Gets the data_sources_used of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The data_sources_used of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._data_sources_used

    @data_sources_used.setter
    def data_sources_used(self, data_sources_used):
        """Sets the data_sources_used of this PromptOptimizationJobStatusResponse.


        :param data_sources_used: The data_sources_used of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """

        self._data_sources_used = data_sources_used

    @property
    def completed_at(self):
        """Gets the completed_at of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The completed_at of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._completed_at

    @completed_at.setter
    def completed_at(self, completed_at):
        """Sets the completed_at of this PromptOptimizationJobStatusResponse.


        :param completed_at: The completed_at of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """

        self._completed_at = completed_at

    @property
    def progress(self):
        """Gets the progress of this PromptOptimizationJobStatusResponse.  # noqa: E501


        :return: The progress of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this PromptOptimizationJobStatusResponse.


        :param progress: The progress of this PromptOptimizationJobStatusResponse.  # noqa: E501
        :type: object
        """

        self._progress = progress

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PromptOptimizationJobStatusResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PromptOptimizationJobStatusResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
