# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PromptTemplateConfigInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_id': 'object',
        'name': 'object',
        'flavor_name': 'object',
        'provider_name': 'object',
        'params': 'object',
        'display_name': 'object',
        'provider_display_name': 'object',
        'model_family': 'object',
        'model_version': 'object'
    }

    attribute_map = {
        'model_id': 'model_id',
        'name': 'name',
        'flavor_name': 'flavor_name',
        'provider_name': 'provider_name',
        'params': 'params',
        'display_name': 'display_name',
        'provider_display_name': 'provider_display_name',
        'model_family': 'model_family',
        'model_version': 'model_version'
    }

    def __init__(self, model_id=None, name=None, flavor_name=None, provider_name=None, params=None, display_name=None, provider_display_name=None, model_family=None, model_version=None):  # noqa: E501
        """PromptTemplateConfigInfo - a model defined in Swagger"""  # noqa: E501
        self._model_id = None
        self._name = None
        self._flavor_name = None
        self._provider_name = None
        self._params = None
        self._display_name = None
        self._provider_display_name = None
        self._model_family = None
        self._model_version = None
        self.discriminator = None
        self.model_id = model_id
        self.name = name
        self.flavor_name = flavor_name
        self.provider_name = provider_name
        self.params = params
        if display_name is not None:
            self.display_name = display_name
        if provider_display_name is not None:
            self.provider_display_name = provider_display_name
        if model_family is not None:
            self.model_family = model_family
        if model_version is not None:
            self.model_version = model_version

    @property
    def model_id(self):
        """Gets the model_id of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The model_id of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """Sets the model_id of this PromptTemplateConfigInfo.


        :param model_id: The model_id of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """
        if model_id is None:
            raise ValueError("Invalid value for `model_id`, must not be `None`")  # noqa: E501

        self._model_id = model_id

    @property
    def name(self):
        """Gets the name of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The name of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PromptTemplateConfigInfo.


        :param name: The name of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def flavor_name(self):
        """Gets the flavor_name of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The flavor_name of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._flavor_name

    @flavor_name.setter
    def flavor_name(self, flavor_name):
        """Sets the flavor_name of this PromptTemplateConfigInfo.


        :param flavor_name: The flavor_name of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """
        if flavor_name is None:
            raise ValueError("Invalid value for `flavor_name`, must not be `None`")  # noqa: E501

        self._flavor_name = flavor_name

    @property
    def provider_name(self):
        """Gets the provider_name of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The provider_name of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name):
        """Sets the provider_name of this PromptTemplateConfigInfo.


        :param provider_name: The provider_name of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """
        if provider_name is None:
            raise ValueError("Invalid value for `provider_name`, must not be `None`")  # noqa: E501

        self._provider_name = provider_name

    @property
    def params(self):
        """Gets the params of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The params of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this PromptTemplateConfigInfo.


        :param params: The params of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """
        if params is None:
            raise ValueError("Invalid value for `params`, must not be `None`")  # noqa: E501

        self._params = params

    @property
    def display_name(self):
        """Gets the display_name of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The display_name of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this PromptTemplateConfigInfo.


        :param display_name: The display_name of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """

        self._display_name = display_name

    @property
    def provider_display_name(self):
        """Gets the provider_display_name of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The provider_display_name of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._provider_display_name

    @provider_display_name.setter
    def provider_display_name(self, provider_display_name):
        """Sets the provider_display_name of this PromptTemplateConfigInfo.


        :param provider_display_name: The provider_display_name of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """

        self._provider_display_name = provider_display_name

    @property
    def model_family(self):
        """Gets the model_family of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The model_family of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._model_family

    @model_family.setter
    def model_family(self, model_family):
        """Sets the model_family of this PromptTemplateConfigInfo.


        :param model_family: The model_family of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """

        self._model_family = model_family

    @property
    def model_version(self):
        """Gets the model_version of this PromptTemplateConfigInfo.  # noqa: E501


        :return: The model_version of this PromptTemplateConfigInfo.  # noqa: E501
        :rtype: object
        """
        return self._model_version

    @model_version.setter
    def model_version(self, model_version):
        """Sets the model_version of this PromptTemplateConfigInfo.


        :param model_version: The model_version of this PromptTemplateConfigInfo.  # noqa: E501
        :type: object
        """

        self._model_version = model_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PromptTemplateConfigInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PromptTemplateConfigInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
