# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecordUpdatePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'new_messages': 'object',
        'eval_results': 'object'
    }

    attribute_map = {
        'new_messages': 'new_messages',
        'eval_results': 'eval_results'
    }

    def __init__(self, new_messages=None, eval_results=None):  # noqa: E501
        """RecordUpdatePayload - a model defined in Swagger"""  # noqa: E501
        self._new_messages = None
        self._eval_results = None
        self.discriminator = None
        if new_messages is not None:
            self.new_messages = new_messages
        if eval_results is not None:
            self.eval_results = eval_results

    @property
    def new_messages(self):
        """Gets the new_messages of this RecordUpdatePayload.  # noqa: E501


        :return: The new_messages of this RecordUpdatePayload.  # noqa: E501
        :rtype: object
        """
        return self._new_messages

    @new_messages.setter
    def new_messages(self, new_messages):
        """Sets the new_messages of this RecordUpdatePayload.


        :param new_messages: The new_messages of this RecordUpdatePayload.  # noqa: E501
        :type: object
        """

        self._new_messages = new_messages

    @property
    def eval_results(self):
        """Gets the eval_results of this RecordUpdatePayload.  # noqa: E501


        :return: The eval_results of this RecordUpdatePayload.  # noqa: E501
        :rtype: object
        """
        return self._eval_results

    @eval_results.setter
    def eval_results(self, eval_results):
        """Sets the eval_results of this RecordUpdatePayload.


        :param eval_results: The eval_results of this RecordUpdatePayload.  # noqa: E501
        :type: object
        """

        self._eval_results = eval_results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecordUpdatePayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecordUpdatePayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
