# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReviewTargetInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'target_type': 'object',
        'entry_ids': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'target_type': 'target_type',
        'entry_ids': 'entry_ids'
    }

    def __init__(self, id=None, name=None, target_type=None, entry_ids=None):  # noqa: E501
        """ReviewTargetInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._target_type = None
        self._entry_ids = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.target_type = target_type
        self.entry_ids = entry_ids

    @property
    def id(self):
        """Gets the id of this ReviewTargetInfo.  # noqa: E501


        :return: The id of this ReviewTargetInfo.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReviewTargetInfo.


        :param id: The id of this ReviewTargetInfo.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ReviewTargetInfo.  # noqa: E501


        :return: The name of this ReviewTargetInfo.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ReviewTargetInfo.


        :param name: The name of this ReviewTargetInfo.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def target_type(self):
        """Gets the target_type of this ReviewTargetInfo.  # noqa: E501


        :return: The target_type of this ReviewTargetInfo.  # noqa: E501
        :rtype: object
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type):
        """Sets the target_type of this ReviewTargetInfo.


        :param target_type: The target_type of this ReviewTargetInfo.  # noqa: E501
        :type: object
        """
        if target_type is None:
            raise ValueError("Invalid value for `target_type`, must not be `None`")  # noqa: E501

        self._target_type = target_type

    @property
    def entry_ids(self):
        """Gets the entry_ids of this ReviewTargetInfo.  # noqa: E501


        :return: The entry_ids of this ReviewTargetInfo.  # noqa: E501
        :rtype: object
        """
        return self._entry_ids

    @entry_ids.setter
    def entry_ids(self, entry_ids):
        """Sets the entry_ids of this ReviewTargetInfo.


        :param entry_ids: The entry_ids of this ReviewTargetInfo.  # noqa: E501
        :type: object
        """
        if entry_ids is None:
            raise ValueError("Invalid value for `entry_ids`, must not be `None`")  # noqa: E501

        self._entry_ids = entry_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReviewTargetInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReviewTargetInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
