# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReviewQueueTarget(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'review_queue_id': 'object',
        'assignee_ids': 'object'
    }

    attribute_map = {
        'review_queue_id': 'review_queue_id',
        'assignee_ids': 'assignee_ids'
    }

    def __init__(self, review_queue_id=None, assignee_ids=None):  # noqa: E501
        """ReviewQueueTarget - a model defined in Swagger"""  # noqa: E501
        self._review_queue_id = None
        self._assignee_ids = None
        self.discriminator = None
        self.review_queue_id = review_queue_id
        if assignee_ids is not None:
            self.assignee_ids = assignee_ids

    @property
    def review_queue_id(self):
        """Gets the review_queue_id of this ReviewQueueTarget.  # noqa: E501


        :return: The review_queue_id of this ReviewQueueTarget.  # noqa: E501
        :rtype: object
        """
        return self._review_queue_id

    @review_queue_id.setter
    def review_queue_id(self, review_queue_id):
        """Sets the review_queue_id of this ReviewQueueTarget.


        :param review_queue_id: The review_queue_id of this ReviewQueueTarget.  # noqa: E501
        :type: object
        """
        if review_queue_id is None:
            raise ValueError("Invalid value for `review_queue_id`, must not be `None`")  # noqa: E501

        self._review_queue_id = review_queue_id

    @property
    def assignee_ids(self):
        """Gets the assignee_ids of this ReviewQueueTarget.  # noqa: E501


        :return: The assignee_ids of this ReviewQueueTarget.  # noqa: E501
        :rtype: object
        """
        return self._assignee_ids

    @assignee_ids.setter
    def assignee_ids(self, assignee_ids):
        """Sets the assignee_ids of this ReviewQueueTarget.


        :param assignee_ids: The assignee_ids of this ReviewQueueTarget.  # noqa: E501
        :type: object
        """

        self._assignee_ids = assignee_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReviewQueueTarget, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReviewQueueTarget):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
