# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReviewThemeDetailInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'description': 'object',
        'entry_type': 'object',
        'record_ids': 'object',
        'created_at': 'object',
        'last_item_added_at': 'object',
        'target_type': 'EvalTargetType',
        'target_id': 'object',
        'target_name': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'entry_type': 'entry_type',
        'record_ids': 'record_ids',
        'created_at': 'created_at',
        'last_item_added_at': 'last_item_added_at',
        'target_type': 'target_type',
        'target_id': 'target_id',
        'target_name': 'target_name'
    }

    def __init__(self, id=None, name=None, description=None, entry_type=None, record_ids=None, created_at=None, last_item_added_at=None, target_type=None, target_id=None, target_name=None):  # noqa: E501
        """ReviewThemeDetailInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._entry_type = None
        self._record_ids = None
        self._created_at = None
        self._last_item_added_at = None
        self._target_type = None
        self._target_id = None
        self._target_name = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.description = description
        self.entry_type = entry_type
        self.record_ids = record_ids
        self.created_at = created_at
        self.last_item_added_at = last_item_added_at
        self.target_type = target_type
        self.target_id = target_id
        self.target_name = target_name

    @property
    def id(self):
        """Gets the id of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The id of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ReviewThemeDetailInfo.


        :param id: The id of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The name of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ReviewThemeDetailInfo.


        :param name: The name of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The description of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ReviewThemeDetailInfo.


        :param description: The description of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def entry_type(self):
        """Gets the entry_type of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The entry_type of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._entry_type

    @entry_type.setter
    def entry_type(self, entry_type):
        """Sets the entry_type of this ReviewThemeDetailInfo.


        :param entry_type: The entry_type of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if entry_type is None:
            raise ValueError("Invalid value for `entry_type`, must not be `None`")  # noqa: E501

        self._entry_type = entry_type

    @property
    def record_ids(self):
        """Gets the record_ids of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The record_ids of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._record_ids

    @record_ids.setter
    def record_ids(self, record_ids):
        """Sets the record_ids of this ReviewThemeDetailInfo.


        :param record_ids: The record_ids of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if record_ids is None:
            raise ValueError("Invalid value for `record_ids`, must not be `None`")  # noqa: E501

        self._record_ids = record_ids

    @property
    def created_at(self):
        """Gets the created_at of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The created_at of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ReviewThemeDetailInfo.


        :param created_at: The created_at of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def last_item_added_at(self):
        """Gets the last_item_added_at of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The last_item_added_at of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._last_item_added_at

    @last_item_added_at.setter
    def last_item_added_at(self, last_item_added_at):
        """Sets the last_item_added_at of this ReviewThemeDetailInfo.


        :param last_item_added_at: The last_item_added_at of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if last_item_added_at is None:
            raise ValueError("Invalid value for `last_item_added_at`, must not be `None`")  # noqa: E501

        self._last_item_added_at = last_item_added_at

    @property
    def target_type(self):
        """Gets the target_type of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The target_type of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: EvalTargetType
        """
        return self._target_type

    @target_type.setter
    def target_type(self, target_type):
        """Sets the target_type of this ReviewThemeDetailInfo.


        :param target_type: The target_type of this ReviewThemeDetailInfo.  # noqa: E501
        :type: EvalTargetType
        """
        if target_type is None:
            raise ValueError("Invalid value for `target_type`, must not be `None`")  # noqa: E501

        self._target_type = target_type

    @property
    def target_id(self):
        """Gets the target_id of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The target_id of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._target_id

    @target_id.setter
    def target_id(self, target_id):
        """Sets the target_id of this ReviewThemeDetailInfo.


        :param target_id: The target_id of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if target_id is None:
            raise ValueError("Invalid value for `target_id`, must not be `None`")  # noqa: E501

        self._target_id = target_id

    @property
    def target_name(self):
        """Gets the target_name of this ReviewThemeDetailInfo.  # noqa: E501


        :return: The target_name of this ReviewThemeDetailInfo.  # noqa: E501
        :rtype: object
        """
        return self._target_name

    @target_name.setter
    def target_name(self, target_name):
        """Sets the target_name of this ReviewThemeDetailInfo.


        :param target_name: The target_name of this ReviewThemeDetailInfo.  # noqa: E501
        :type: object
        """
        if target_name is None:
            raise ValueError("Invalid value for `target_name`, must not be `None`")  # noqa: E501

        self._target_name = target_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReviewThemeDetailInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReviewThemeDetailInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
