# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SessionSearchInfoWithChildren(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_id': 'object',
        'session_metadata': 'SessionMetadataInfo',
        'usage': 'UsageInfo',
        'custom_metadata': 'object',
        'test_run_id': 'object',
        'children': 'object'
    }

    attribute_map = {
        'session_id': 'session_id',
        'session_metadata': 'session_metadata',
        'usage': 'usage',
        'custom_metadata': 'custom_metadata',
        'test_run_id': 'test_run_id',
        'children': 'children'
    }

    def __init__(self, session_id=None, session_metadata=None, usage=None, custom_metadata=None, test_run_id=None, children=None):  # noqa: E501
        """SessionSearchInfoWithChildren - a model defined in Swagger"""  # noqa: E501
        self._session_id = None
        self._session_metadata = None
        self._usage = None
        self._custom_metadata = None
        self._test_run_id = None
        self._children = None
        self.discriminator = None
        self.session_id = session_id
        self.session_metadata = session_metadata
        self.usage = usage
        self.custom_metadata = custom_metadata
        self.test_run_id = test_run_id
        if children is not None:
            self.children = children

    @property
    def session_id(self):
        """Gets the session_id of this SessionSearchInfoWithChildren.  # noqa: E501


        :return: The session_id of this SessionSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this SessionSearchInfoWithChildren.


        :param session_id: The session_id of this SessionSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def session_metadata(self):
        """Gets the session_metadata of this SessionSearchInfoWithChildren.  # noqa: E501


        :return: The session_metadata of this SessionSearchInfoWithChildren.  # noqa: E501
        :rtype: SessionMetadataInfo
        """
        return self._session_metadata

    @session_metadata.setter
    def session_metadata(self, session_metadata):
        """Sets the session_metadata of this SessionSearchInfoWithChildren.


        :param session_metadata: The session_metadata of this SessionSearchInfoWithChildren.  # noqa: E501
        :type: SessionMetadataInfo
        """
        if session_metadata is None:
            raise ValueError("Invalid value for `session_metadata`, must not be `None`")  # noqa: E501

        self._session_metadata = session_metadata

    @property
    def usage(self):
        """Gets the usage of this SessionSearchInfoWithChildren.  # noqa: E501


        :return: The usage of this SessionSearchInfoWithChildren.  # noqa: E501
        :rtype: UsageInfo
        """
        return self._usage

    @usage.setter
    def usage(self, usage):
        """Sets the usage of this SessionSearchInfoWithChildren.


        :param usage: The usage of this SessionSearchInfoWithChildren.  # noqa: E501
        :type: UsageInfo
        """
        if usage is None:
            raise ValueError("Invalid value for `usage`, must not be `None`")  # noqa: E501

        self._usage = usage

    @property
    def custom_metadata(self):
        """Gets the custom_metadata of this SessionSearchInfoWithChildren.  # noqa: E501


        :return: The custom_metadata of this SessionSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._custom_metadata

    @custom_metadata.setter
    def custom_metadata(self, custom_metadata):
        """Sets the custom_metadata of this SessionSearchInfoWithChildren.


        :param custom_metadata: The custom_metadata of this SessionSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if custom_metadata is None:
            raise ValueError("Invalid value for `custom_metadata`, must not be `None`")  # noqa: E501

        self._custom_metadata = custom_metadata

    @property
    def test_run_id(self):
        """Gets the test_run_id of this SessionSearchInfoWithChildren.  # noqa: E501


        :return: The test_run_id of this SessionSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._test_run_id

    @test_run_id.setter
    def test_run_id(self, test_run_id):
        """Sets the test_run_id of this SessionSearchInfoWithChildren.


        :param test_run_id: The test_run_id of this SessionSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if test_run_id is None:
            raise ValueError("Invalid value for `test_run_id`, must not be `None`")  # noqa: E501

        self._test_run_id = test_run_id

    @property
    def children(self):
        """Gets the children of this SessionSearchInfoWithChildren.  # noqa: E501


        :return: The children of this SessionSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this SessionSearchInfoWithChildren.


        :param children: The children of this SessionSearchInfoWithChildren.  # noqa: E501
        :type: object
        """

        self._children = children

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SessionSearchInfoWithChildren, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionSearchInfoWithChildren):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
