# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SessionFilterReplicationInfo1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'filter_model': 'object',
        'is_team_filter': 'object',
        'created_by': 'object',
        'created_at': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'filter_model': 'filter_model',
        'is_team_filter': 'is_team_filter',
        'created_by': 'created_by',
        'created_at': 'created_at'
    }

    def __init__(self, id=None, name=None, filter_model=None, is_team_filter=None, created_by=None, created_at=None):  # noqa: E501
        """SessionFilterReplicationInfo1 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._filter_model = None
        self._is_team_filter = None
        self._created_by = None
        self._created_at = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.filter_model = filter_model
        self.is_team_filter = is_team_filter
        self.created_by = created_by
        self.created_at = created_at

    @property
    def id(self):
        """Gets the id of this SessionFilterReplicationInfo1.  # noqa: E501


        :return: The id of this SessionFilterReplicationInfo1.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SessionFilterReplicationInfo1.


        :param id: The id of this SessionFilterReplicationInfo1.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this SessionFilterReplicationInfo1.  # noqa: E501


        :return: The name of this SessionFilterReplicationInfo1.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SessionFilterReplicationInfo1.


        :param name: The name of this SessionFilterReplicationInfo1.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def filter_model(self):
        """Gets the filter_model of this SessionFilterReplicationInfo1.  # noqa: E501


        :return: The filter_model of this SessionFilterReplicationInfo1.  # noqa: E501
        :rtype: object
        """
        return self._filter_model

    @filter_model.setter
    def filter_model(self, filter_model):
        """Sets the filter_model of this SessionFilterReplicationInfo1.


        :param filter_model: The filter_model of this SessionFilterReplicationInfo1.  # noqa: E501
        :type: object
        """
        if filter_model is None:
            raise ValueError("Invalid value for `filter_model`, must not be `None`")  # noqa: E501

        self._filter_model = filter_model

    @property
    def is_team_filter(self):
        """Gets the is_team_filter of this SessionFilterReplicationInfo1.  # noqa: E501


        :return: The is_team_filter of this SessionFilterReplicationInfo1.  # noqa: E501
        :rtype: object
        """
        return self._is_team_filter

    @is_team_filter.setter
    def is_team_filter(self, is_team_filter):
        """Sets the is_team_filter of this SessionFilterReplicationInfo1.


        :param is_team_filter: The is_team_filter of this SessionFilterReplicationInfo1.  # noqa: E501
        :type: object
        """
        if is_team_filter is None:
            raise ValueError("Invalid value for `is_team_filter`, must not be `None`")  # noqa: E501

        self._is_team_filter = is_team_filter

    @property
    def created_by(self):
        """Gets the created_by of this SessionFilterReplicationInfo1.  # noqa: E501


        :return: The created_by of this SessionFilterReplicationInfo1.  # noqa: E501
        :rtype: object
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this SessionFilterReplicationInfo1.


        :param created_by: The created_by of this SessionFilterReplicationInfo1.  # noqa: E501
        :type: object
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by

    @property
    def created_at(self):
        """Gets the created_at of this SessionFilterReplicationInfo1.  # noqa: E501


        :return: The created_at of this SessionFilterReplicationInfo1.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SessionFilterReplicationInfo1.


        :param created_at: The created_at of this SessionFilterReplicationInfo1.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SessionFilterReplicationInfo1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionFilterReplicationInfo1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
