# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SessionTableMeta(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filter_values': 'TableFilterValues',
        'eval_config': 'EvaluationConfig',
        'input_names': 'object',
        'metadata_keys': 'object',
        'feedback_keys': 'object',
        'trace_feedback_keys': 'object',
        'trace_metadata_keys': 'object'
    }

    attribute_map = {
        'filter_values': 'filter_values',
        'eval_config': 'eval_config',
        'input_names': 'input_names',
        'metadata_keys': 'metadata_keys',
        'feedback_keys': 'feedback_keys',
        'trace_feedback_keys': 'trace_feedback_keys',
        'trace_metadata_keys': 'trace_metadata_keys'
    }

    def __init__(self, filter_values=None, eval_config=None, input_names=None, metadata_keys=None, feedback_keys=None, trace_feedback_keys=None, trace_metadata_keys=None):  # noqa: E501
        """SessionTableMeta - a model defined in Swagger"""  # noqa: E501
        self._filter_values = None
        self._eval_config = None
        self._input_names = None
        self._metadata_keys = None
        self._feedback_keys = None
        self._trace_feedback_keys = None
        self._trace_metadata_keys = None
        self.discriminator = None
        self.filter_values = filter_values
        self.eval_config = eval_config
        self.input_names = input_names
        self.metadata_keys = metadata_keys
        self.feedback_keys = feedback_keys
        self.trace_feedback_keys = trace_feedback_keys
        self.trace_metadata_keys = trace_metadata_keys

    @property
    def filter_values(self):
        """Gets the filter_values of this SessionTableMeta.  # noqa: E501


        :return: The filter_values of this SessionTableMeta.  # noqa: E501
        :rtype: TableFilterValues
        """
        return self._filter_values

    @filter_values.setter
    def filter_values(self, filter_values):
        """Sets the filter_values of this SessionTableMeta.


        :param filter_values: The filter_values of this SessionTableMeta.  # noqa: E501
        :type: TableFilterValues
        """
        if filter_values is None:
            raise ValueError("Invalid value for `filter_values`, must not be `None`")  # noqa: E501

        self._filter_values = filter_values

    @property
    def eval_config(self):
        """Gets the eval_config of this SessionTableMeta.  # noqa: E501


        :return: The eval_config of this SessionTableMeta.  # noqa: E501
        :rtype: EvaluationConfig
        """
        return self._eval_config

    @eval_config.setter
    def eval_config(self, eval_config):
        """Sets the eval_config of this SessionTableMeta.


        :param eval_config: The eval_config of this SessionTableMeta.  # noqa: E501
        :type: EvaluationConfig
        """
        if eval_config is None:
            raise ValueError("Invalid value for `eval_config`, must not be `None`")  # noqa: E501

        self._eval_config = eval_config

    @property
    def input_names(self):
        """Gets the input_names of this SessionTableMeta.  # noqa: E501


        :return: The input_names of this SessionTableMeta.  # noqa: E501
        :rtype: object
        """
        return self._input_names

    @input_names.setter
    def input_names(self, input_names):
        """Sets the input_names of this SessionTableMeta.


        :param input_names: The input_names of this SessionTableMeta.  # noqa: E501
        :type: object
        """
        if input_names is None:
            raise ValueError("Invalid value for `input_names`, must not be `None`")  # noqa: E501

        self._input_names = input_names

    @property
    def metadata_keys(self):
        """Gets the metadata_keys of this SessionTableMeta.  # noqa: E501


        :return: The metadata_keys of this SessionTableMeta.  # noqa: E501
        :rtype: object
        """
        return self._metadata_keys

    @metadata_keys.setter
    def metadata_keys(self, metadata_keys):
        """Sets the metadata_keys of this SessionTableMeta.


        :param metadata_keys: The metadata_keys of this SessionTableMeta.  # noqa: E501
        :type: object
        """
        if metadata_keys is None:
            raise ValueError("Invalid value for `metadata_keys`, must not be `None`")  # noqa: E501

        self._metadata_keys = metadata_keys

    @property
    def feedback_keys(self):
        """Gets the feedback_keys of this SessionTableMeta.  # noqa: E501


        :return: The feedback_keys of this SessionTableMeta.  # noqa: E501
        :rtype: object
        """
        return self._feedback_keys

    @feedback_keys.setter
    def feedback_keys(self, feedback_keys):
        """Sets the feedback_keys of this SessionTableMeta.


        :param feedback_keys: The feedback_keys of this SessionTableMeta.  # noqa: E501
        :type: object
        """
        if feedback_keys is None:
            raise ValueError("Invalid value for `feedback_keys`, must not be `None`")  # noqa: E501

        self._feedback_keys = feedback_keys

    @property
    def trace_feedback_keys(self):
        """Gets the trace_feedback_keys of this SessionTableMeta.  # noqa: E501


        :return: The trace_feedback_keys of this SessionTableMeta.  # noqa: E501
        :rtype: object
        """
        return self._trace_feedback_keys

    @trace_feedback_keys.setter
    def trace_feedback_keys(self, trace_feedback_keys):
        """Sets the trace_feedback_keys of this SessionTableMeta.


        :param trace_feedback_keys: The trace_feedback_keys of this SessionTableMeta.  # noqa: E501
        :type: object
        """
        if trace_feedback_keys is None:
            raise ValueError("Invalid value for `trace_feedback_keys`, must not be `None`")  # noqa: E501

        self._trace_feedback_keys = trace_feedback_keys

    @property
    def trace_metadata_keys(self):
        """Gets the trace_metadata_keys of this SessionTableMeta.  # noqa: E501


        :return: The trace_metadata_keys of this SessionTableMeta.  # noqa: E501
        :rtype: object
        """
        return self._trace_metadata_keys

    @trace_metadata_keys.setter
    def trace_metadata_keys(self, trace_metadata_keys):
        """Sets the trace_metadata_keys of this SessionTableMeta.


        :param trace_metadata_keys: The trace_metadata_keys of this SessionTableMeta.  # noqa: E501
        :type: object
        """
        if trace_metadata_keys is None:
            raise ValueError("Invalid value for `trace_metadata_keys`, must not be `None`")  # noqa: E501

        self._trace_metadata_keys = trace_metadata_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SessionTableMeta, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionTableMeta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
