# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SessionSummaryInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'start_time': 'object',
        'end_time': 'object',
        'aggregate': 'Aggregate',
        'custom_metadata': 'object',
        'children': 'object',
        'kind': 'object',
        'is_truncated': 'object'
    }

    attribute_map = {
        'id': 'id',
        'start_time': 'start_time',
        'end_time': 'end_time',
        'aggregate': 'aggregate',
        'custom_metadata': 'custom_metadata',
        'children': 'children',
        'kind': 'kind',
        'is_truncated': 'is_truncated'
    }

    def __init__(self, id=None, start_time=None, end_time=None, aggregate=None, custom_metadata=None, children=None, kind=None, is_truncated=None):  # noqa: E501
        """SessionSummaryInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._start_time = None
        self._end_time = None
        self._aggregate = None
        self._custom_metadata = None
        self._children = None
        self._kind = None
        self._is_truncated = None
        self.discriminator = None
        self.id = id
        self.start_time = start_time
        self.end_time = end_time
        self.aggregate = aggregate
        self.custom_metadata = custom_metadata
        self.children = children
        if kind is not None:
            self.kind = kind
        if is_truncated is not None:
            self.is_truncated = is_truncated

    @property
    def id(self):
        """Gets the id of this SessionSummaryInfo.  # noqa: E501


        :return: The id of this SessionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SessionSummaryInfo.


        :param id: The id of this SessionSummaryInfo.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def start_time(self):
        """Gets the start_time of this SessionSummaryInfo.  # noqa: E501


        :return: The start_time of this SessionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this SessionSummaryInfo.


        :param start_time: The start_time of this SessionSummaryInfo.  # noqa: E501
        :type: object
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this SessionSummaryInfo.  # noqa: E501


        :return: The end_time of this SessionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this SessionSummaryInfo.


        :param end_time: The end_time of this SessionSummaryInfo.  # noqa: E501
        :type: object
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    @property
    def aggregate(self):
        """Gets the aggregate of this SessionSummaryInfo.  # noqa: E501


        :return: The aggregate of this SessionSummaryInfo.  # noqa: E501
        :rtype: Aggregate
        """
        return self._aggregate

    @aggregate.setter
    def aggregate(self, aggregate):
        """Sets the aggregate of this SessionSummaryInfo.


        :param aggregate: The aggregate of this SessionSummaryInfo.  # noqa: E501
        :type: Aggregate
        """
        if aggregate is None:
            raise ValueError("Invalid value for `aggregate`, must not be `None`")  # noqa: E501

        self._aggregate = aggregate

    @property
    def custom_metadata(self):
        """Gets the custom_metadata of this SessionSummaryInfo.  # noqa: E501


        :return: The custom_metadata of this SessionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._custom_metadata

    @custom_metadata.setter
    def custom_metadata(self, custom_metadata):
        """Sets the custom_metadata of this SessionSummaryInfo.


        :param custom_metadata: The custom_metadata of this SessionSummaryInfo.  # noqa: E501
        :type: object
        """
        if custom_metadata is None:
            raise ValueError("Invalid value for `custom_metadata`, must not be `None`")  # noqa: E501

        self._custom_metadata = custom_metadata

    @property
    def children(self):
        """Gets the children of this SessionSummaryInfo.  # noqa: E501


        :return: The children of this SessionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this SessionSummaryInfo.


        :param children: The children of this SessionSummaryInfo.  # noqa: E501
        :type: object
        """
        if children is None:
            raise ValueError("Invalid value for `children`, must not be `None`")  # noqa: E501

        self._children = children

    @property
    def kind(self):
        """Gets the kind of this SessionSummaryInfo.  # noqa: E501


        :return: The kind of this SessionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this SessionSummaryInfo.


        :param kind: The kind of this SessionSummaryInfo.  # noqa: E501
        :type: object
        """

        self._kind = kind

    @property
    def is_truncated(self):
        """Gets the is_truncated of this SessionSummaryInfo.  # noqa: E501


        :return: The is_truncated of this SessionSummaryInfo.  # noqa: E501
        :rtype: object
        """
        return self._is_truncated

    @is_truncated.setter
    def is_truncated(self, is_truncated):
        """Sets the is_truncated of this SessionSummaryInfo.


        :param is_truncated: The is_truncated of this SessionSummaryInfo.  # noqa: E501
        :type: object
        """

        self._is_truncated = is_truncated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SessionSummaryInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionSummaryInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
