# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShardInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'object',
        'primaries': 'object',
        'replicas': 'object'
    }

    attribute_map = {
        'total': 'total',
        'primaries': 'primaries',
        'replicas': 'replicas'
    }

    def __init__(self, total=None, primaries=None, replicas=None):  # noqa: E501
        """ShardInfo - a model defined in Swagger"""  # noqa: E501
        self._total = None
        self._primaries = None
        self._replicas = None
        self.discriminator = None
        self.total = total
        self.primaries = primaries
        self.replicas = replicas

    @property
    def total(self):
        """Gets the total of this ShardInfo.  # noqa: E501


        :return: The total of this ShardInfo.  # noqa: E501
        :rtype: object
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this ShardInfo.


        :param total: The total of this ShardInfo.  # noqa: E501
        :type: object
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    @property
    def primaries(self):
        """Gets the primaries of this ShardInfo.  # noqa: E501


        :return: The primaries of this ShardInfo.  # noqa: E501
        :rtype: object
        """
        return self._primaries

    @primaries.setter
    def primaries(self, primaries):
        """Sets the primaries of this ShardInfo.


        :param primaries: The primaries of this ShardInfo.  # noqa: E501
        :type: object
        """
        if primaries is None:
            raise ValueError("Invalid value for `primaries`, must not be `None`")  # noqa: E501

        self._primaries = primaries

    @property
    def replicas(self):
        """Gets the replicas of this ShardInfo.  # noqa: E501


        :return: The replicas of this ShardInfo.  # noqa: E501
        :rtype: object
        """
        return self._replicas

    @replicas.setter
    def replicas(self, replicas):
        """Sets the replicas of this ShardInfo.


        :param replicas: The replicas of this ShardInfo.  # noqa: E501
        :type: object
        """
        if replicas is None:
            raise ValueError("Invalid value for `replicas`, must not be `None`")  # noqa: E501

        self._replicas = replicas

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShardInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShardInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
