# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SummaryStatistics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'human_evaluation': 'object',
        'auto_evaluation': 'object',
        'client_evaluation': 'object'
    }

    attribute_map = {
        'human_evaluation': 'human_evaluation',
        'auto_evaluation': 'auto_evaluation',
        'client_evaluation': 'client_evaluation'
    }

    def __init__(self, human_evaluation=None, auto_evaluation=None, client_evaluation=None):  # noqa: E501
        """SummaryStatistics - a model defined in Swagger"""  # noqa: E501
        self._human_evaluation = None
        self._auto_evaluation = None
        self._client_evaluation = None
        self.discriminator = None
        if human_evaluation is not None:
            self.human_evaluation = human_evaluation
        if auto_evaluation is not None:
            self.auto_evaluation = auto_evaluation
        if client_evaluation is not None:
            self.client_evaluation = client_evaluation

    @property
    def human_evaluation(self):
        """Gets the human_evaluation of this SummaryStatistics.  # noqa: E501


        :return: The human_evaluation of this SummaryStatistics.  # noqa: E501
        :rtype: object
        """
        return self._human_evaluation

    @human_evaluation.setter
    def human_evaluation(self, human_evaluation):
        """Sets the human_evaluation of this SummaryStatistics.


        :param human_evaluation: The human_evaluation of this SummaryStatistics.  # noqa: E501
        :type: object
        """

        self._human_evaluation = human_evaluation

    @property
    def auto_evaluation(self):
        """Gets the auto_evaluation of this SummaryStatistics.  # noqa: E501


        :return: The auto_evaluation of this SummaryStatistics.  # noqa: E501
        :rtype: object
        """
        return self._auto_evaluation

    @auto_evaluation.setter
    def auto_evaluation(self, auto_evaluation):
        """Sets the auto_evaluation of this SummaryStatistics.


        :param auto_evaluation: The auto_evaluation of this SummaryStatistics.  # noqa: E501
        :type: object
        """

        self._auto_evaluation = auto_evaluation

    @property
    def client_evaluation(self):
        """Gets the client_evaluation of this SummaryStatistics.  # noqa: E501


        :return: The client_evaluation of this SummaryStatistics.  # noqa: E501
        :rtype: object
        """
        return self._client_evaluation

    @client_evaluation.setter
    def client_evaluation(self, client_evaluation):
        """Sets the client_evaluation of this SummaryStatistics.


        :param client_evaluation: The client_evaluation of this SummaryStatistics.  # noqa: E501
        :type: object
        """

        self._client_evaluation = client_evaluation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SummaryStatistics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SummaryStatistics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
