# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TemplateMessageWithVariables(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role': 'object',
        'template': 'object',
        'variables': 'object',
        'media_references': 'object',
        'media_slots': 'object'
    }

    attribute_map = {
        'role': 'role',
        'template': 'template',
        'variables': 'variables',
        'media_references': 'media_references',
        'media_slots': 'media_slots'
    }

    def __init__(self, role=None, template=None, variables=None, media_references=None, media_slots=None):  # noqa: E501
        """TemplateMessageWithVariables - a model defined in Swagger"""  # noqa: E501
        self._role = None
        self._template = None
        self._variables = None
        self._media_references = None
        self._media_slots = None
        self.discriminator = None
        self.role = role
        self.template = template
        self.variables = variables
        self.media_references = media_references
        self.media_slots = media_slots

    @property
    def role(self):
        """Gets the role of this TemplateMessageWithVariables.  # noqa: E501


        :return: The role of this TemplateMessageWithVariables.  # noqa: E501
        :rtype: object
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this TemplateMessageWithVariables.


        :param role: The role of this TemplateMessageWithVariables.  # noqa: E501
        :type: object
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def template(self):
        """Gets the template of this TemplateMessageWithVariables.  # noqa: E501


        :return: The template of this TemplateMessageWithVariables.  # noqa: E501
        :rtype: object
        """
        return self._template

    @template.setter
    def template(self, template):
        """Sets the template of this TemplateMessageWithVariables.


        :param template: The template of this TemplateMessageWithVariables.  # noqa: E501
        :type: object
        """
        if template is None:
            raise ValueError("Invalid value for `template`, must not be `None`")  # noqa: E501

        self._template = template

    @property
    def variables(self):
        """Gets the variables of this TemplateMessageWithVariables.  # noqa: E501


        :return: The variables of this TemplateMessageWithVariables.  # noqa: E501
        :rtype: object
        """
        return self._variables

    @variables.setter
    def variables(self, variables):
        """Sets the variables of this TemplateMessageWithVariables.


        :param variables: The variables of this TemplateMessageWithVariables.  # noqa: E501
        :type: object
        """
        if variables is None:
            raise ValueError("Invalid value for `variables`, must not be `None`")  # noqa: E501

        self._variables = variables

    @property
    def media_references(self):
        """Gets the media_references of this TemplateMessageWithVariables.  # noqa: E501


        :return: The media_references of this TemplateMessageWithVariables.  # noqa: E501
        :rtype: object
        """
        return self._media_references

    @media_references.setter
    def media_references(self, media_references):
        """Sets the media_references of this TemplateMessageWithVariables.


        :param media_references: The media_references of this TemplateMessageWithVariables.  # noqa: E501
        :type: object
        """
        if media_references is None:
            raise ValueError("Invalid value for `media_references`, must not be `None`")  # noqa: E501

        self._media_references = media_references

    @property
    def media_slots(self):
        """Gets the media_slots of this TemplateMessageWithVariables.  # noqa: E501


        :return: The media_slots of this TemplateMessageWithVariables.  # noqa: E501
        :rtype: object
        """
        return self._media_slots

    @media_slots.setter
    def media_slots(self, media_slots):
        """Sets the media_slots of this TemplateMessageWithVariables.


        :param media_slots: The media_slots of this TemplateMessageWithVariables.  # noqa: E501
        :type: object
        """
        if media_slots is None:
            raise ValueError("Invalid value for `media_slots`, must not be `None`")  # noqa: E501

        self._media_slots = media_slots

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TemplateMessageWithVariables, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TemplateMessageWithVariables):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
