# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TestCaseComparisonPreference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'preferred_original': 'object',
        'preferred_test_run_id': 'object'
    }

    attribute_map = {
        'preferred_original': 'preferred_original',
        'preferred_test_run_id': 'preferred_test_run_id'
    }

    def __init__(self, preferred_original=None, preferred_test_run_id=None):  # noqa: E501
        """TestCaseComparisonPreference - a model defined in Swagger"""  # noqa: E501
        self._preferred_original = None
        self._preferred_test_run_id = None
        self.discriminator = None
        if preferred_original is not None:
            self.preferred_original = preferred_original
        if preferred_test_run_id is not None:
            self.preferred_test_run_id = preferred_test_run_id

    @property
    def preferred_original(self):
        """Gets the preferred_original of this TestCaseComparisonPreference.  # noqa: E501


        :return: The preferred_original of this TestCaseComparisonPreference.  # noqa: E501
        :rtype: object
        """
        return self._preferred_original

    @preferred_original.setter
    def preferred_original(self, preferred_original):
        """Sets the preferred_original of this TestCaseComparisonPreference.


        :param preferred_original: The preferred_original of this TestCaseComparisonPreference.  # noqa: E501
        :type: object
        """

        self._preferred_original = preferred_original

    @property
    def preferred_test_run_id(self):
        """Gets the preferred_test_run_id of this TestCaseComparisonPreference.  # noqa: E501


        :return: The preferred_test_run_id of this TestCaseComparisonPreference.  # noqa: E501
        :rtype: object
        """
        return self._preferred_test_run_id

    @preferred_test_run_id.setter
    def preferred_test_run_id(self, preferred_test_run_id):
        """Sets the preferred_test_run_id of this TestCaseComparisonPreference.


        :param preferred_test_run_id: The preferred_test_run_id of this TestCaseComparisonPreference.  # noqa: E501
        :type: object
        """

        self._preferred_test_run_id = preferred_test_run_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestCaseComparisonPreference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestCaseComparisonPreference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
