# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TestCaseComparisonInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'test_case_id': 'object',
        'test_run_id': 'object',
        'display_index': 'object',
        'test_case_count': 'object',
        'comparison_sides': 'object',
        'preference': 'TestCaseComparisonPreference',
        'next_test_case_id': 'object',
        'prev_test_case_id': 'object',
        'comparison_id': 'object'
    }

    attribute_map = {
        'test_case_id': 'test_case_id',
        'test_run_id': 'test_run_id',
        'display_index': 'display_index',
        'test_case_count': 'test_case_count',
        'comparison_sides': 'comparison_sides',
        'preference': 'preference',
        'next_test_case_id': 'next_test_case_id',
        'prev_test_case_id': 'prev_test_case_id',
        'comparison_id': 'comparison_id'
    }

    def __init__(self, test_case_id=None, test_run_id=None, display_index=None, test_case_count=None, comparison_sides=None, preference=None, next_test_case_id=None, prev_test_case_id=None, comparison_id=None):  # noqa: E501
        """TestCaseComparisonInfo - a model defined in Swagger"""  # noqa: E501
        self._test_case_id = None
        self._test_run_id = None
        self._display_index = None
        self._test_case_count = None
        self._comparison_sides = None
        self._preference = None
        self._next_test_case_id = None
        self._prev_test_case_id = None
        self._comparison_id = None
        self.discriminator = None
        self.test_case_id = test_case_id
        self.test_run_id = test_run_id
        self.display_index = display_index
        self.test_case_count = test_case_count
        self.comparison_sides = comparison_sides
        self.preference = preference
        if next_test_case_id is not None:
            self.next_test_case_id = next_test_case_id
        if prev_test_case_id is not None:
            self.prev_test_case_id = prev_test_case_id
        if comparison_id is not None:
            self.comparison_id = comparison_id

    @property
    def test_case_id(self):
        """Gets the test_case_id of this TestCaseComparisonInfo.  # noqa: E501


        :return: The test_case_id of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: object
        """
        return self._test_case_id

    @test_case_id.setter
    def test_case_id(self, test_case_id):
        """Sets the test_case_id of this TestCaseComparisonInfo.


        :param test_case_id: The test_case_id of this TestCaseComparisonInfo.  # noqa: E501
        :type: object
        """
        if test_case_id is None:
            raise ValueError("Invalid value for `test_case_id`, must not be `None`")  # noqa: E501

        self._test_case_id = test_case_id

    @property
    def test_run_id(self):
        """Gets the test_run_id of this TestCaseComparisonInfo.  # noqa: E501


        :return: The test_run_id of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: object
        """
        return self._test_run_id

    @test_run_id.setter
    def test_run_id(self, test_run_id):
        """Sets the test_run_id of this TestCaseComparisonInfo.


        :param test_run_id: The test_run_id of this TestCaseComparisonInfo.  # noqa: E501
        :type: object
        """
        if test_run_id is None:
            raise ValueError("Invalid value for `test_run_id`, must not be `None`")  # noqa: E501

        self._test_run_id = test_run_id

    @property
    def display_index(self):
        """Gets the display_index of this TestCaseComparisonInfo.  # noqa: E501


        :return: The display_index of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: object
        """
        return self._display_index

    @display_index.setter
    def display_index(self, display_index):
        """Sets the display_index of this TestCaseComparisonInfo.


        :param display_index: The display_index of this TestCaseComparisonInfo.  # noqa: E501
        :type: object
        """
        if display_index is None:
            raise ValueError("Invalid value for `display_index`, must not be `None`")  # noqa: E501

        self._display_index = display_index

    @property
    def test_case_count(self):
        """Gets the test_case_count of this TestCaseComparisonInfo.  # noqa: E501


        :return: The test_case_count of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: object
        """
        return self._test_case_count

    @test_case_count.setter
    def test_case_count(self, test_case_count):
        """Sets the test_case_count of this TestCaseComparisonInfo.


        :param test_case_count: The test_case_count of this TestCaseComparisonInfo.  # noqa: E501
        :type: object
        """
        if test_case_count is None:
            raise ValueError("Invalid value for `test_case_count`, must not be `None`")  # noqa: E501

        self._test_case_count = test_case_count

    @property
    def comparison_sides(self):
        """Gets the comparison_sides of this TestCaseComparisonInfo.  # noqa: E501


        :return: The comparison_sides of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: object
        """
        return self._comparison_sides

    @comparison_sides.setter
    def comparison_sides(self, comparison_sides):
        """Sets the comparison_sides of this TestCaseComparisonInfo.


        :param comparison_sides: The comparison_sides of this TestCaseComparisonInfo.  # noqa: E501
        :type: object
        """
        if comparison_sides is None:
            raise ValueError("Invalid value for `comparison_sides`, must not be `None`")  # noqa: E501

        self._comparison_sides = comparison_sides

    @property
    def preference(self):
        """Gets the preference of this TestCaseComparisonInfo.  # noqa: E501


        :return: The preference of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: TestCaseComparisonPreference
        """
        return self._preference

    @preference.setter
    def preference(self, preference):
        """Sets the preference of this TestCaseComparisonInfo.


        :param preference: The preference of this TestCaseComparisonInfo.  # noqa: E501
        :type: TestCaseComparisonPreference
        """
        if preference is None:
            raise ValueError("Invalid value for `preference`, must not be `None`")  # noqa: E501

        self._preference = preference

    @property
    def next_test_case_id(self):
        """Gets the next_test_case_id of this TestCaseComparisonInfo.  # noqa: E501


        :return: The next_test_case_id of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: object
        """
        return self._next_test_case_id

    @next_test_case_id.setter
    def next_test_case_id(self, next_test_case_id):
        """Sets the next_test_case_id of this TestCaseComparisonInfo.


        :param next_test_case_id: The next_test_case_id of this TestCaseComparisonInfo.  # noqa: E501
        :type: object
        """

        self._next_test_case_id = next_test_case_id

    @property
    def prev_test_case_id(self):
        """Gets the prev_test_case_id of this TestCaseComparisonInfo.  # noqa: E501


        :return: The prev_test_case_id of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: object
        """
        return self._prev_test_case_id

    @prev_test_case_id.setter
    def prev_test_case_id(self, prev_test_case_id):
        """Sets the prev_test_case_id of this TestCaseComparisonInfo.


        :param prev_test_case_id: The prev_test_case_id of this TestCaseComparisonInfo.  # noqa: E501
        :type: object
        """

        self._prev_test_case_id = prev_test_case_id

    @property
    def comparison_id(self):
        """Gets the comparison_id of this TestCaseComparisonInfo.  # noqa: E501


        :return: The comparison_id of this TestCaseComparisonInfo.  # noqa: E501
        :rtype: object
        """
        return self._comparison_id

    @comparison_id.setter
    def comparison_id(self, comparison_id):
        """Sets the comparison_id of this TestCaseComparisonInfo.


        :param comparison_id: The comparison_id of this TestCaseComparisonInfo.  # noqa: E501
        :type: object
        """

        self._comparison_id = comparison_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestCaseComparisonInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestCaseComparisonInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
