# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TestRunInsightInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'description': 'object',
        'test_case_ids': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'test_case_ids': 'test_case_ids'
    }

    def __init__(self, id=None, name=None, description=None, test_case_ids=None):  # noqa: E501
        """TestRunInsightInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._test_case_ids = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.description = description
        self.test_case_ids = test_case_ids

    @property
    def id(self):
        """Gets the id of this TestRunInsightInfo.  # noqa: E501


        :return: The id of this TestRunInsightInfo.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TestRunInsightInfo.


        :param id: The id of this TestRunInsightInfo.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this TestRunInsightInfo.  # noqa: E501


        :return: The name of this TestRunInsightInfo.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TestRunInsightInfo.


        :param name: The name of this TestRunInsightInfo.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this TestRunInsightInfo.  # noqa: E501


        :return: The description of this TestRunInsightInfo.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TestRunInsightInfo.


        :param description: The description of this TestRunInsightInfo.  # noqa: E501
        :type: object
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def test_case_ids(self):
        """Gets the test_case_ids of this TestRunInsightInfo.  # noqa: E501


        :return: The test_case_ids of this TestRunInsightInfo.  # noqa: E501
        :rtype: object
        """
        return self._test_case_ids

    @test_case_ids.setter
    def test_case_ids(self, test_case_ids):
        """Sets the test_case_ids of this TestRunInsightInfo.


        :param test_case_ids: The test_case_ids of this TestRunInsightInfo.  # noqa: E501
        :type: object
        """
        if test_case_ids is None:
            raise ValueError("Invalid value for `test_case_ids`, must not be `None`")  # noqa: E501

        self._test_case_ids = test_case_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestRunInsightInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestRunInsightInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
