# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TestRunResponseInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'description': 'object',
        'created_at': 'object',
        'prompt_name': 'object',
        'prompt_version': 'object',
        'model_name': 'object',
        'sessions_count': 'object',
        'summary_statistics': 'SummaryStatistics'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'created_at': 'created_at',
        'prompt_name': 'prompt_name',
        'prompt_version': 'prompt_version',
        'model_name': 'model_name',
        'sessions_count': 'sessions_count',
        'summary_statistics': 'summary_statistics'
    }

    def __init__(self, id=None, name=None, description=None, created_at=None, prompt_name=None, prompt_version=None, model_name=None, sessions_count=None, summary_statistics=None):  # noqa: E501
        """TestRunResponseInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._created_at = None
        self._prompt_name = None
        self._prompt_version = None
        self._model_name = None
        self._sessions_count = None
        self._summary_statistics = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.description = description
        self.created_at = created_at
        self.prompt_name = prompt_name
        self.prompt_version = prompt_version
        self.model_name = model_name
        self.sessions_count = sessions_count
        self.summary_statistics = summary_statistics

    @property
    def id(self):
        """Gets the id of this TestRunResponseInfo.  # noqa: E501


        :return: The id of this TestRunResponseInfo.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TestRunResponseInfo.


        :param id: The id of this TestRunResponseInfo.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this TestRunResponseInfo.  # noqa: E501


        :return: The name of this TestRunResponseInfo.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TestRunResponseInfo.


        :param name: The name of this TestRunResponseInfo.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this TestRunResponseInfo.  # noqa: E501


        :return: The description of this TestRunResponseInfo.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TestRunResponseInfo.


        :param description: The description of this TestRunResponseInfo.  # noqa: E501
        :type: object
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def created_at(self):
        """Gets the created_at of this TestRunResponseInfo.  # noqa: E501


        :return: The created_at of this TestRunResponseInfo.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this TestRunResponseInfo.


        :param created_at: The created_at of this TestRunResponseInfo.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def prompt_name(self):
        """Gets the prompt_name of this TestRunResponseInfo.  # noqa: E501


        :return: The prompt_name of this TestRunResponseInfo.  # noqa: E501
        :rtype: object
        """
        return self._prompt_name

    @prompt_name.setter
    def prompt_name(self, prompt_name):
        """Sets the prompt_name of this TestRunResponseInfo.


        :param prompt_name: The prompt_name of this TestRunResponseInfo.  # noqa: E501
        :type: object
        """
        if prompt_name is None:
            raise ValueError("Invalid value for `prompt_name`, must not be `None`")  # noqa: E501

        self._prompt_name = prompt_name

    @property
    def prompt_version(self):
        """Gets the prompt_version of this TestRunResponseInfo.  # noqa: E501


        :return: The prompt_version of this TestRunResponseInfo.  # noqa: E501
        :rtype: object
        """
        return self._prompt_version

    @prompt_version.setter
    def prompt_version(self, prompt_version):
        """Sets the prompt_version of this TestRunResponseInfo.


        :param prompt_version: The prompt_version of this TestRunResponseInfo.  # noqa: E501
        :type: object
        """
        if prompt_version is None:
            raise ValueError("Invalid value for `prompt_version`, must not be `None`")  # noqa: E501

        self._prompt_version = prompt_version

    @property
    def model_name(self):
        """Gets the model_name of this TestRunResponseInfo.  # noqa: E501


        :return: The model_name of this TestRunResponseInfo.  # noqa: E501
        :rtype: object
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this TestRunResponseInfo.


        :param model_name: The model_name of this TestRunResponseInfo.  # noqa: E501
        :type: object
        """
        if model_name is None:
            raise ValueError("Invalid value for `model_name`, must not be `None`")  # noqa: E501

        self._model_name = model_name

    @property
    def sessions_count(self):
        """Gets the sessions_count of this TestRunResponseInfo.  # noqa: E501


        :return: The sessions_count of this TestRunResponseInfo.  # noqa: E501
        :rtype: object
        """
        return self._sessions_count

    @sessions_count.setter
    def sessions_count(self, sessions_count):
        """Sets the sessions_count of this TestRunResponseInfo.


        :param sessions_count: The sessions_count of this TestRunResponseInfo.  # noqa: E501
        :type: object
        """
        if sessions_count is None:
            raise ValueError("Invalid value for `sessions_count`, must not be `None`")  # noqa: E501

        self._sessions_count = sessions_count

    @property
    def summary_statistics(self):
        """Gets the summary_statistics of this TestRunResponseInfo.  # noqa: E501


        :return: The summary_statistics of this TestRunResponseInfo.  # noqa: E501
        :rtype: SummaryStatistics
        """
        return self._summary_statistics

    @summary_statistics.setter
    def summary_statistics(self, summary_statistics):
        """Sets the summary_statistics of this TestRunResponseInfo.


        :param summary_statistics: The summary_statistics of this TestRunResponseInfo.  # noqa: E501
        :type: SummaryStatistics
        """
        if summary_statistics is None:
            raise ValueError("Invalid value for `summary_statistics`, must not be `None`")  # noqa: E501

        self._summary_statistics = summary_statistics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestRunResponseInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestRunResponseInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
