# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TestCaseUploadWithMedia(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'inputs': 'object',
        'history': 'object',
        'output': 'object',
        'metadata': 'object',
        'media_inputs': 'object',
        'output_message': 'object'
    }

    attribute_map = {
        'inputs': 'inputs',
        'history': 'history',
        'output': 'output',
        'metadata': 'metadata',
        'media_inputs': 'media_inputs',
        'output_message': 'output_message'
    }

    def __init__(self, inputs=None, history=None, output=None, metadata=None, media_inputs=None, output_message=None):  # noqa: E501
        """TestCaseUploadWithMedia - a model defined in Swagger"""  # noqa: E501
        self._inputs = None
        self._history = None
        self._output = None
        self._metadata = None
        self._media_inputs = None
        self._output_message = None
        self.discriminator = None
        self.inputs = inputs
        if history is not None:
            self.history = history
        if output is not None:
            self.output = output
        if metadata is not None:
            self.metadata = metadata
        if media_inputs is not None:
            self.media_inputs = media_inputs
        if output_message is not None:
            self.output_message = output_message

    @property
    def inputs(self):
        """Gets the inputs of this TestCaseUploadWithMedia.  # noqa: E501


        :return: The inputs of this TestCaseUploadWithMedia.  # noqa: E501
        :rtype: object
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this TestCaseUploadWithMedia.


        :param inputs: The inputs of this TestCaseUploadWithMedia.  # noqa: E501
        :type: object
        """
        if inputs is None:
            raise ValueError("Invalid value for `inputs`, must not be `None`")  # noqa: E501

        self._inputs = inputs

    @property
    def history(self):
        """Gets the history of this TestCaseUploadWithMedia.  # noqa: E501


        :return: The history of this TestCaseUploadWithMedia.  # noqa: E501
        :rtype: object
        """
        return self._history

    @history.setter
    def history(self, history):
        """Sets the history of this TestCaseUploadWithMedia.


        :param history: The history of this TestCaseUploadWithMedia.  # noqa: E501
        :type: object
        """

        self._history = history

    @property
    def output(self):
        """Gets the output of this TestCaseUploadWithMedia.  # noqa: E501


        :return: The output of this TestCaseUploadWithMedia.  # noqa: E501
        :rtype: object
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TestCaseUploadWithMedia.


        :param output: The output of this TestCaseUploadWithMedia.  # noqa: E501
        :type: object
        """

        self._output = output

    @property
    def metadata(self):
        """Gets the metadata of this TestCaseUploadWithMedia.  # noqa: E501


        :return: The metadata of this TestCaseUploadWithMedia.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this TestCaseUploadWithMedia.


        :param metadata: The metadata of this TestCaseUploadWithMedia.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    @property
    def media_inputs(self):
        """Gets the media_inputs of this TestCaseUploadWithMedia.  # noqa: E501


        :return: The media_inputs of this TestCaseUploadWithMedia.  # noqa: E501
        :rtype: object
        """
        return self._media_inputs

    @media_inputs.setter
    def media_inputs(self, media_inputs):
        """Sets the media_inputs of this TestCaseUploadWithMedia.


        :param media_inputs: The media_inputs of this TestCaseUploadWithMedia.  # noqa: E501
        :type: object
        """

        self._media_inputs = media_inputs

    @property
    def output_message(self):
        """Gets the output_message of this TestCaseUploadWithMedia.  # noqa: E501


        :return: The output_message of this TestCaseUploadWithMedia.  # noqa: E501
        :rtype: object
        """
        return self._output_message

    @output_message.setter
    def output_message(self, output_message):
        """Sets the output_message of this TestCaseUploadWithMedia.


        :param output_message: The output_message of this TestCaseUploadWithMedia.  # noqa: E501
        :type: object
        """

        self._output_message = output_message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TestCaseUploadWithMedia, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestCaseUploadWithMedia):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
