# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TotalCountWithGrowthPercentage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'object',
        'growth_percentage': 'object'
    }

    attribute_map = {
        'count': 'count',
        'growth_percentage': 'growth_percentage'
    }

    def __init__(self, count=None, growth_percentage=None):  # noqa: E501
        """TotalCountWithGrowthPercentage - a model defined in Swagger"""  # noqa: E501
        self._count = None
        self._growth_percentage = None
        self.discriminator = None
        self.count = count
        self.growth_percentage = growth_percentage

    @property
    def count(self):
        """Gets the count of this TotalCountWithGrowthPercentage.  # noqa: E501


        :return: The count of this TotalCountWithGrowthPercentage.  # noqa: E501
        :rtype: object
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this TotalCountWithGrowthPercentage.


        :param count: The count of this TotalCountWithGrowthPercentage.  # noqa: E501
        :type: object
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def growth_percentage(self):
        """Gets the growth_percentage of this TotalCountWithGrowthPercentage.  # noqa: E501


        :return: The growth_percentage of this TotalCountWithGrowthPercentage.  # noqa: E501
        :rtype: object
        """
        return self._growth_percentage

    @growth_percentage.setter
    def growth_percentage(self, growth_percentage):
        """Sets the growth_percentage of this TotalCountWithGrowthPercentage.


        :param growth_percentage: The growth_percentage of this TotalCountWithGrowthPercentage.  # noqa: E501
        :type: object
        """
        if growth_percentage is None:
            raise ValueError("Invalid value for `growth_percentage`, must not be `None`")  # noqa: E501

        self._growth_percentage = growth_percentage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TotalCountWithGrowthPercentage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TotalCountWithGrowthPercentage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
