# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TraceSearchInfoWithChildren(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'session_id': 'object',
        'trace_id': 'object',
        'review_queue_id': 'object',
        'trace_metadata': 'object',
        'custom_metadata': 'object',
        'customer_feedback': 'object',
        'input': 'object',
        'output': 'object',
        'evaluation_results': 'EvaluationResultsInfo',
        'children': 'object'
    }

    attribute_map = {
        'session_id': 'session_id',
        'trace_id': 'trace_id',
        'review_queue_id': 'review_queue_id',
        'trace_metadata': 'trace_metadata',
        'custom_metadata': 'custom_metadata',
        'customer_feedback': 'customer_feedback',
        'input': 'input',
        'output': 'output',
        'evaluation_results': 'evaluation_results',
        'children': 'children'
    }

    def __init__(self, session_id=None, trace_id=None, review_queue_id=None, trace_metadata=None, custom_metadata=None, customer_feedback=None, input=None, output=None, evaluation_results=None, children=None):  # noqa: E501
        """TraceSearchInfoWithChildren - a model defined in Swagger"""  # noqa: E501
        self._session_id = None
        self._trace_id = None
        self._review_queue_id = None
        self._trace_metadata = None
        self._custom_metadata = None
        self._customer_feedback = None
        self._input = None
        self._output = None
        self._evaluation_results = None
        self._children = None
        self.discriminator = None
        self.session_id = session_id
        self.trace_id = trace_id
        self.review_queue_id = review_queue_id
        self.trace_metadata = trace_metadata
        self.custom_metadata = custom_metadata
        self.customer_feedback = customer_feedback
        self.input = input
        self.output = output
        self.evaluation_results = evaluation_results
        if children is not None:
            self.children = children

    @property
    def session_id(self):
        """Gets the session_id of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The session_id of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this TraceSearchInfoWithChildren.


        :param session_id: The session_id of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if session_id is None:
            raise ValueError("Invalid value for `session_id`, must not be `None`")  # noqa: E501

        self._session_id = session_id

    @property
    def trace_id(self):
        """Gets the trace_id of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The trace_id of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._trace_id

    @trace_id.setter
    def trace_id(self, trace_id):
        """Sets the trace_id of this TraceSearchInfoWithChildren.


        :param trace_id: The trace_id of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if trace_id is None:
            raise ValueError("Invalid value for `trace_id`, must not be `None`")  # noqa: E501

        self._trace_id = trace_id

    @property
    def review_queue_id(self):
        """Gets the review_queue_id of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The review_queue_id of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._review_queue_id

    @review_queue_id.setter
    def review_queue_id(self, review_queue_id):
        """Sets the review_queue_id of this TraceSearchInfoWithChildren.


        :param review_queue_id: The review_queue_id of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if review_queue_id is None:
            raise ValueError("Invalid value for `review_queue_id`, must not be `None`")  # noqa: E501

        self._review_queue_id = review_queue_id

    @property
    def trace_metadata(self):
        """Gets the trace_metadata of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The trace_metadata of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._trace_metadata

    @trace_metadata.setter
    def trace_metadata(self, trace_metadata):
        """Sets the trace_metadata of this TraceSearchInfoWithChildren.


        :param trace_metadata: The trace_metadata of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if trace_metadata is None:
            raise ValueError("Invalid value for `trace_metadata`, must not be `None`")  # noqa: E501

        self._trace_metadata = trace_metadata

    @property
    def custom_metadata(self):
        """Gets the custom_metadata of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The custom_metadata of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._custom_metadata

    @custom_metadata.setter
    def custom_metadata(self, custom_metadata):
        """Sets the custom_metadata of this TraceSearchInfoWithChildren.


        :param custom_metadata: The custom_metadata of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if custom_metadata is None:
            raise ValueError("Invalid value for `custom_metadata`, must not be `None`")  # noqa: E501

        self._custom_metadata = custom_metadata

    @property
    def customer_feedback(self):
        """Gets the customer_feedback of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The customer_feedback of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._customer_feedback

    @customer_feedback.setter
    def customer_feedback(self, customer_feedback):
        """Sets the customer_feedback of this TraceSearchInfoWithChildren.


        :param customer_feedback: The customer_feedback of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if customer_feedback is None:
            raise ValueError("Invalid value for `customer_feedback`, must not be `None`")  # noqa: E501

        self._customer_feedback = customer_feedback

    @property
    def input(self):
        """Gets the input of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The input of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this TraceSearchInfoWithChildren.


        :param input: The input of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if input is None:
            raise ValueError("Invalid value for `input`, must not be `None`")  # noqa: E501

        self._input = input

    @property
    def output(self):
        """Gets the output of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The output of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TraceSearchInfoWithChildren.


        :param output: The output of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """
        if output is None:
            raise ValueError("Invalid value for `output`, must not be `None`")  # noqa: E501

        self._output = output

    @property
    def evaluation_results(self):
        """Gets the evaluation_results of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The evaluation_results of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: EvaluationResultsInfo
        """
        return self._evaluation_results

    @evaluation_results.setter
    def evaluation_results(self, evaluation_results):
        """Sets the evaluation_results of this TraceSearchInfoWithChildren.


        :param evaluation_results: The evaluation_results of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: EvaluationResultsInfo
        """
        if evaluation_results is None:
            raise ValueError("Invalid value for `evaluation_results`, must not be `None`")  # noqa: E501

        self._evaluation_results = evaluation_results

    @property
    def children(self):
        """Gets the children of this TraceSearchInfoWithChildren.  # noqa: E501


        :return: The children of this TraceSearchInfoWithChildren.  # noqa: E501
        :rtype: object
        """
        return self._children

    @children.setter
    def children(self, children):
        """Sets the children of this TraceSearchInfoWithChildren.


        :param children: The children of this TraceSearchInfoWithChildren.  # noqa: E501
        :type: object
        """

        self._children = children

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TraceSearchInfoWithChildren, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TraceSearchInfoWithChildren):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
