# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TraceTestCaseInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'test_case_id': 'object',
        'input': 'JSONValue',
        'output': 'object',
        'custom_metadata': 'object',
        'test_case_type': 'object'
    }

    attribute_map = {
        'test_case_id': 'test_case_id',
        'input': 'input',
        'output': 'output',
        'custom_metadata': 'custom_metadata',
        'test_case_type': 'test_case_type'
    }

    def __init__(self, test_case_id=None, input=None, output=None, custom_metadata=None, test_case_type=None):  # noqa: E501
        """TraceTestCaseInfo - a model defined in Swagger"""  # noqa: E501
        self._test_case_id = None
        self._input = None
        self._output = None
        self._custom_metadata = None
        self._test_case_type = None
        self.discriminator = None
        self.test_case_id = test_case_id
        self.input = input
        self.output = output
        if custom_metadata is not None:
            self.custom_metadata = custom_metadata
        if test_case_type is not None:
            self.test_case_type = test_case_type

    @property
    def test_case_id(self):
        """Gets the test_case_id of this TraceTestCaseInfo.  # noqa: E501


        :return: The test_case_id of this TraceTestCaseInfo.  # noqa: E501
        :rtype: object
        """
        return self._test_case_id

    @test_case_id.setter
    def test_case_id(self, test_case_id):
        """Sets the test_case_id of this TraceTestCaseInfo.


        :param test_case_id: The test_case_id of this TraceTestCaseInfo.  # noqa: E501
        :type: object
        """
        if test_case_id is None:
            raise ValueError("Invalid value for `test_case_id`, must not be `None`")  # noqa: E501

        self._test_case_id = test_case_id

    @property
    def input(self):
        """Gets the input of this TraceTestCaseInfo.  # noqa: E501


        :return: The input of this TraceTestCaseInfo.  # noqa: E501
        :rtype: JSONValue
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this TraceTestCaseInfo.


        :param input: The input of this TraceTestCaseInfo.  # noqa: E501
        :type: JSONValue
        """
        if input is None:
            raise ValueError("Invalid value for `input`, must not be `None`")  # noqa: E501

        self._input = input

    @property
    def output(self):
        """Gets the output of this TraceTestCaseInfo.  # noqa: E501


        :return: The output of this TraceTestCaseInfo.  # noqa: E501
        :rtype: object
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TraceTestCaseInfo.


        :param output: The output of this TraceTestCaseInfo.  # noqa: E501
        :type: object
        """
        if output is None:
            raise ValueError("Invalid value for `output`, must not be `None`")  # noqa: E501

        self._output = output

    @property
    def custom_metadata(self):
        """Gets the custom_metadata of this TraceTestCaseInfo.  # noqa: E501


        :return: The custom_metadata of this TraceTestCaseInfo.  # noqa: E501
        :rtype: object
        """
        return self._custom_metadata

    @custom_metadata.setter
    def custom_metadata(self, custom_metadata):
        """Sets the custom_metadata of this TraceTestCaseInfo.


        :param custom_metadata: The custom_metadata of this TraceTestCaseInfo.  # noqa: E501
        :type: object
        """

        self._custom_metadata = custom_metadata

    @property
    def test_case_type(self):
        """Gets the test_case_type of this TraceTestCaseInfo.  # noqa: E501


        :return: The test_case_type of this TraceTestCaseInfo.  # noqa: E501
        :rtype: object
        """
        return self._test_case_type

    @test_case_type.setter
    def test_case_type(self, test_case_type):
        """Sets the test_case_type of this TraceTestCaseInfo.


        :param test_case_type: The test_case_type of this TraceTestCaseInfo.  # noqa: E501
        :type: object
        """

        self._test_case_type = test_case_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TraceTestCaseInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TraceTestCaseInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
