# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VertexMessage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'parts': 'object',
        'role': 'object'
    }

    attribute_map = {
        'parts': 'parts',
        'role': 'role'
    }

    def __init__(self, parts=None, role=None):  # noqa: E501
        """VertexMessage - a model defined in Swagger"""  # noqa: E501
        self._parts = None
        self._role = None
        self.discriminator = None
        self.parts = parts
        if role is not None:
            self.role = role

    @property
    def parts(self):
        """Gets the parts of this VertexMessage.  # noqa: E501


        :return: The parts of this VertexMessage.  # noqa: E501
        :rtype: object
        """
        return self._parts

    @parts.setter
    def parts(self, parts):
        """Sets the parts of this VertexMessage.


        :param parts: The parts of this VertexMessage.  # noqa: E501
        :type: object
        """
        if parts is None:
            raise ValueError("Invalid value for `parts`, must not be `None`")  # noqa: E501

        self._parts = parts

    @property
    def role(self):
        """Gets the role of this VertexMessage.  # noqa: E501


        :return: The role of this VertexMessage.  # noqa: E501
        :rtype: object
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this VertexMessage.


        :param role: The role of this VertexMessage.  # noqa: E501
        :type: object
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VertexMessage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VertexMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
