# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VertexInlineDataPart(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'inline_data': 'VertexInlineData'
    }

    attribute_map = {
        'inline_data': 'inlineData'
    }

    def __init__(self, inline_data=None):  # noqa: E501
        """VertexInlineDataPart - a model defined in Swagger"""  # noqa: E501
        self._inline_data = None
        self.discriminator = None
        self.inline_data = inline_data

    @property
    def inline_data(self):
        """Gets the inline_data of this VertexInlineDataPart.  # noqa: E501


        :return: The inline_data of this VertexInlineDataPart.  # noqa: E501
        :rtype: VertexInlineData
        """
        return self._inline_data

    @inline_data.setter
    def inline_data(self, inline_data):
        """Sets the inline_data of this VertexInlineDataPart.


        :param inline_data: The inline_data of this VertexInlineDataPart.  # noqa: E501
        :type: VertexInlineData
        """
        if inline_data is None:
            raise ValueError("Invalid value for `inline_data`, must not be `None`")  # noqa: E501

        self._inline_data = inline_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VertexInlineDataPart, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VertexInlineDataPart):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
