# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.project_member_info import ProjectMemberInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectMemberInfo(unittest.TestCase):
    """ProjectMemberInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectMemberInfo(self):
        """Test ProjectMemberInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.project_member_info.ProjectMemberInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
