# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_test_run_insights_response import GetTestRunInsightsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetTestRunInsightsResponse(unittest.TestCase):
    """GetTestRunInsightsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTestRunInsightsResponse(self):
        """Test GetTestRunInsightsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_test_run_insights_response.GetTestRunInsightsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
