# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.agents_api import AgentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self):
        self.api = AgentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_delete_agent(self):
        """Test case for delete_delete_agent

        Delete Agent  # noqa: E501
        """
        pass

    def test_get_get_agent(self):
        """Test case for get_get_agent

        Get Agent  # noqa: E501
        """
        pass

    def test_get_get_agents(self):
        """Test case for get_get_agents

        List Agents  # noqa: E501
        """
        pass

    def test_patch_update_agent(self):
        """Test case for patch_update_agent

        Update Agent  # noqa: E501
        """
        pass

    def test_post_create_agent(self):
        """Test case for post_create_agent

        Create Agent  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
