# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.context_source_info import ContextSourceInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestContextSourceInfo(unittest.TestCase):
    """ContextSourceInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContextSourceInfo(self):
        """Test ContextSourceInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.context_source_info.ContextSourceInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
