# coding: utf-8

"""
    server.app.app_initializer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.open_ai_file_block import OpenAIFileBlock  # noqa: E501
from swagger_client.rest import ApiException


class TestOpenAIFileBlock(unittest.TestCase):
    """OpenAIFileBlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenAIFileBlock(self):
        """Test OpenAIFileBlock"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.open_ai_file_block.OpenAIFileBlock()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
