# coding: utf-8

"""
    server.app.app_initializer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.configuration_api import ConfigurationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_delete_environment(self):
        """Test case for delete_delete_environment

        Delete Environment  # noqa: E501
        """
        pass

    def test_delete_delete_user(self):
        """Test case for delete_delete_user

        Delete User  # noqa: E501
        """
        pass

    def test_delete_remove_member(self):
        """Test case for delete_remove_member

        Remove Project Member  # noqa: E501
        """
        pass

    def test_get_get_project(self):
        """Test case for get_get_project

        Get Project  # noqa: E501
        """
        pass

    def test_get_get_projects(self):
        """Test case for get_get_projects

        List Projects  # noqa: E501
        """
        pass

    def test_get_get_user(self):
        """Test case for get_get_user

        Get User  # noqa: E501
        """
        pass

    def test_get_list_environments(self):
        """Test case for get_list_environments

        List Environments  # noqa: E501
        """
        pass

    def test_get_list_members(self):
        """Test case for get_list_members

        List Project Members  # noqa: E501
        """
        pass

    def test_get_list_users(self):
        """Test case for get_list_users

        List Users  # noqa: E501
        """
        pass

    def test_patch_update_environment(self):
        """Test case for patch_update_environment

        Update Environment  # noqa: E501
        """
        pass

    def test_patch_update_member(self):
        """Test case for patch_update_member

        Update Project Member  # noqa: E501
        """
        pass

    def test_patch_update_user(self):
        """Test case for patch_update_user

        Update User  # noqa: E501
        """
        pass

    def test_post_add_member(self):
        """Test case for post_add_member

        Add Project Member  # noqa: E501
        """
        pass

    def test_post_create_environment(self):
        """Test case for post_create_environment

        Create Environment  # noqa: E501
        """
        pass

    def test_post_create_project(self):
        """Test case for post_create_project

        Create Project  # noqa: E501
        """
        pass

    def test_post_create_user(self):
        """Test case for post_create_user

        Create User  # noqa: E501
        """
        pass

    def test_put_update_project(self):
        """Test case for put_update_project

        Update Project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
