# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.llm_param_number_range import LLMParamNumberRange  # noqa: E501
from swagger_client.rest import ApiException


class TestLLMParamNumberRange(unittest.TestCase):
    """LLMParamNumberRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLLMParamNumberRange(self):
        """Test LLMParamNumberRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.llm_param_number_range.LLMParamNumberRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
