# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.models_api import ModelsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestModelsApi(unittest.TestCase):
    """ModelsApi unit test stubs"""

    def setUp(self):
        self.api = ModelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_delete_model(self):
        """Test case for delete_delete_model

        Delete Model  # noqa: E501
        """
        pass

    def test_get_get_model(self):
        """Test case for get_get_model

        Get Model  # noqa: E501
        """
        pass

    def test_get_list_models(self):
        """Test case for get_list_models

        List Models  # noqa: E501
        """
        pass

    def test_post_replicate_model(self):
        """Test case for post_replicate_model

        Create Model  # noqa: E501
        """
        pass

    def test_put_update_model(self):
        """Test case for put_update_model

        Update Model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
