# coding: utf-8

"""
    server.app.app_initializer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.open_ai_audio_base64 import OpenAIAudioBase64  # noqa: E501
from swagger_client.rest import ApiException


class TestOpenAIAudioBase64(unittest.TestCase):
    """OpenAIAudioBase64 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenAIAudioBase64(self):
        """Test OpenAIAudioBase64"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.open_ai_audio_base64.OpenAIAudioBase64()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
