# coding: utf-8

"""
    server.app.app_initializer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_bulk_delete_agent_dataset_test_cases(self):
        """Test case for delete_bulk_delete_agent_dataset_test_cases

        """
        pass

    def test_delete_bulk_delete_prompt_dataset_test_cases(self):
        """Test case for delete_bulk_delete_prompt_dataset_test_cases

        """
        pass

    def test_delete_delete_agent(self):
        """Test case for delete_delete_agent

        """
        pass

    def test_delete_delete_agent_dataset(self):
        """Test case for delete_delete_agent_dataset

        """
        pass

    def test_delete_delete_agent_dataset_test_case(self):
        """Test case for delete_delete_agent_dataset_test_case

        """
        pass

    def test_delete_delete_criteria_version(self):
        """Test case for delete_delete_criteria_version

        """
        pass

    def test_delete_delete_environment(self):
        """Test case for delete_delete_environment

        """
        pass

    def test_delete_delete_evaluation_criteria(self):
        """Test case for delete_delete_evaluation_criteria

        """
        pass

    def test_delete_delete_project(self):
        """Test case for delete_delete_project

        """
        pass

    def test_delete_delete_prompt_dataset(self):
        """Test case for delete_delete_prompt_dataset

        """
        pass

    def test_delete_delete_prompt_dataset_test_case(self):
        """Test case for delete_delete_prompt_dataset_test_case

        """
        pass

    def test_delete_delete_prompt_template(self):
        """Test case for delete_delete_prompt_template

        """
        pass

    def test_delete_delete_session(self):
        """Test case for delete_delete_session

        """
        pass

    def test_delete_delete_template_version(self):
        """Test case for delete_delete_template_version

        """
        pass

    def test_delete_delete_theme(self):
        """Test case for delete_delete_theme

        """
        pass

    def test_delete_delete_user(self):
        """Test case for delete_delete_user

        """
        pass

    def test_delete_remove_member(self):
        """Test case for delete_remove_member

        """
        pass

    def test_get_get_agent(self):
        """Test case for get_get_agent

        """
        pass

    def test_get_get_agent_dataset(self):
        """Test case for get_get_agent_dataset

        """
        pass

    def test_get_get_agent_dataset_test_case(self):
        """Test case for get_get_agent_dataset_test_case

        """
        pass

    def test_get_get_agent_dataset_test_cases(self):
        """Test case for get_get_agent_dataset_test_cases

        """
        pass

    def test_get_get_agent_datasets(self):
        """Test case for get_get_agent_datasets

        """
        pass

    def test_get_get_agents(self):
        """Test case for get_get_agents

        """
        pass

    def test_get_get_all_by_environment(self):
        """Test case for get_get_all_by_environment

        """
        pass

    def test_get_get_by_id(self):
        """Test case for get_get_by_id

        """
        pass

    def test_get_get_by_name(self):
        """Test case for get_get_by_name

        """
        pass

    def test_get_get_by_name_and_environment(self):
        """Test case for get_get_by_name_and_environment

        """
        pass

    def test_get_get_by_template_version_id(self):
        """Test case for get_get_by_template_version_id

        """
        pass

    def test_get_get_criteria_version(self):
        """Test case for get_get_criteria_version

        """
        pass

    def test_get_get_evaluation_criteria(self):
        """Test case for get_get_evaluation_criteria

        """
        pass

    def test_get_get_project(self):
        """Test case for get_get_project

        """
        pass

    def test_get_get_projects(self):
        """Test case for get_get_projects

        """
        pass

    def test_get_get_prompt_dataset(self):
        """Test case for get_get_prompt_dataset

        """
        pass

    def test_get_get_prompt_dataset_test_case(self):
        """Test case for get_get_prompt_dataset_test_case

        """
        pass

    def test_get_get_prompt_dataset_test_cases(self):
        """Test case for get_get_prompt_dataset_test_cases

        """
        pass

    def test_get_get_prompt_datasets(self):
        """Test case for get_get_prompt_datasets

        """
        pass

    def test_get_get_prompt_template(self):
        """Test case for get_get_prompt_template

        """
        pass

    def test_get_get_sessions_filtered(self):
        """Test case for get_get_sessions_filtered

        """
        pass

    def test_get_get_test_case_datasets(self):
        """Test case for get_get_test_case_datasets

        """
        pass

    def test_get_get_test_cases_by_id(self):
        """Test case for get_get_test_cases_by_id

        """
        pass

    def test_get_get_test_cases_by_name(self):
        """Test case for get_get_test_cases_by_name

        """
        pass

    def test_get_get_test_run_results(self):
        """Test case for get_get_test_run_results

        """
        pass

    def test_get_get_test_runs(self):
        """Test case for get_get_test_runs

        """
        pass

    def test_get_get_theme(self):
        """Test case for get_get_theme

        """
        pass

    def test_get_get_user(self):
        """Test case for get_get_user

        """
        pass

    def test_get_list_criteria_versions(self):
        """Test case for get_list_criteria_versions

        """
        pass

    def test_get_list_environments(self):
        """Test case for get_list_environments

        """
        pass

    def test_get_list_evaluation_criteria(self):
        """Test case for get_list_evaluation_criteria

        """
        pass

    def test_get_list_members(self):
        """Test case for get_list_members

        """
        pass

    def test_get_list_prompt_template_versions(self):
        """Test case for get_list_prompt_template_versions

        """
        pass

    def test_get_list_prompt_templates(self):
        """Test case for get_list_prompt_templates

        """
        pass

    def test_get_list_themes(self):
        """Test case for get_list_themes

        """
        pass

    def test_get_list_users(self):
        """Test case for get_list_users

        """
        pass

    def test_patch_disable_criteria(self):
        """Test case for patch_disable_criteria

        """
        pass

    def test_patch_enable_criteria(self):
        """Test case for patch_enable_criteria

        """
        pass

    def test_patch_reorder_criteria(self):
        """Test case for patch_reorder_criteria

        """
        pass

    def test_patch_update_agent(self):
        """Test case for patch_update_agent

        """
        pass

    def test_patch_update_agent_dataset(self):
        """Test case for patch_update_agent_dataset

        """
        pass

    def test_patch_update_agent_dataset_test_case(self):
        """Test case for patch_update_agent_dataset_test_case

        """
        pass

    def test_patch_update_environment(self):
        """Test case for patch_update_environment

        """
        pass

    def test_patch_update_evaluation_criteria(self):
        """Test case for patch_update_evaluation_criteria

        """
        pass

    def test_patch_update_member(self):
        """Test case for patch_update_member

        """
        pass

    def test_patch_update_prompt_dataset(self):
        """Test case for patch_update_prompt_dataset

        """
        pass

    def test_patch_update_prompt_dataset_test_case(self):
        """Test case for patch_update_prompt_dataset_test_case

        """
        pass

    def test_patch_update_prompt_template(self):
        """Test case for patch_update_prompt_template

        """
        pass

    def test_patch_update_user(self):
        """Test case for patch_update_user

        """
        pass

    def test_post_add_member(self):
        """Test case for post_add_member

        """
        pass

    def test_post_bulk_create_agent_dataset_test_cases(self):
        """Test case for post_bulk_create_agent_dataset_test_cases

        """
        pass

    def test_post_bulk_create_prompt_dataset_test_cases(self):
        """Test case for post_bulk_create_prompt_dataset_test_cases

        """
        pass

    def test_post_create_agent(self):
        """Test case for post_create_agent

        """
        pass

    def test_post_create_agent_dataset(self):
        """Test case for post_create_agent_dataset

        """
        pass

    def test_post_create_completion_feedback(self):
        """Test case for post_create_completion_feedback

        """
        pass

    def test_post_create_criteria_version(self):
        """Test case for post_create_criteria_version

        """
        pass

    def test_post_create_environment(self):
        """Test case for post_create_environment

        """
        pass

    def test_post_create_evaluation_criteria(self):
        """Test case for post_create_evaluation_criteria

        """
        pass

    def test_post_create_project(self):
        """Test case for post_create_project

        """
        pass

    def test_post_create_prompt_dataset(self):
        """Test case for post_create_prompt_dataset

        """
        pass

    def test_post_create_prompt_template(self):
        """Test case for post_create_prompt_template

        """
        pass

    def test_post_create_template_version_by_id(self):
        """Test case for post_create_template_version_by_id

        """
        pass

    def test_post_create_template_version_by_name(self):
        """Test case for post_create_template_version_by_name

        """
        pass

    def test_post_create_user(self):
        """Test case for post_create_user

        """
        pass

    def test_post_create_with_test_cases(self):
        """Test case for post_create_with_test_cases

        """
        pass

    def test_post_deploy_criteria_version(self):
        """Test case for post_deploy_criteria_version

        """
        pass

    def test_post_get_all_completion_summaries(self):
        """Test case for post_get_all_completion_summaries

        """
        pass

    def test_post_get_bound_by_name_and_environment(self):
        """Test case for post_get_bound_by_name_and_environment

        """
        pass

    def test_post_get_bound_by_template_version_id(self):
        """Test case for post_get_bound_by_template_version_id

        """
        pass

    def test_post_get_completion_summary(self):
        """Test case for post_get_completion_summary

        """
        pass

    def test_post_metrics(self):
        """Test case for post_metrics

        """
        pass

    def test_post_record(self):
        """Test case for post_record

        """
        pass

    def test_post_record_0(self):
        """Test case for post_record_0

        """
        pass

    def test_post_replicate_theme(self):
        """Test case for post_replicate_theme

        """
        pass

    def test_post_trace_feedback(self):
        """Test case for post_trace_feedback

        """
        pass

    def test_post_traces(self):
        """Test case for post_traces

        """
        pass

    def test_post_update(self):
        """Test case for post_update

        """
        pass

    def test_post_update_template_version_environments(self):
        """Test case for post_update_template_version_environments

        """
        pass

    def test_post_upload_test_cases(self):
        """Test case for post_upload_test_cases

        """
        pass

    def test_put_update_project(self):
        """Test case for put_update_project

        """
        pass

    def test_put_update_theme(self):
        """Test case for put_update_theme

        """
        pass


if __name__ == '__main__':
    unittest.main()
