# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.insights_api import InsightsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInsightsApi(unittest.TestCase):
    """InsightsApi unit test stubs"""

    def setUp(self):
        self.api = InsightsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_get_insights(self):
        """Test case for get_get_insights

        Get Insights  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
