# coding: utf-8

"""
    server.app.app_initializer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.observability_api import ObservabilityApi  # noqa: E501
from swagger_client.rest import ApiException


class TestObservabilityApi(unittest.TestCase):
    """ObservabilityApi unit test stubs"""

    def setUp(self):
        self.api = ObservabilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_delete_session(self):
        """Test case for delete_delete_session

        Delete Session  # noqa: E501
        """
        pass

    def test_patch_update_session_metadata(self):
        """Test case for patch_update_session_metadata

        Update Session Metadata  # noqa: E501
        """
        pass

    def test_patch_update_trace_metadata(self):
        """Test case for patch_update_trace_metadata

        Update Trace Metadata  # noqa: E501
        """
        pass

    def test_post_create_completion_feedback(self):
        """Test case for post_create_completion_feedback

        Add Completion Feedback  # noqa: E501
        """
        pass

    def test_post_record_completion(self):
        """Test case for post_record_completion

        Record Completion  # noqa: E501
        """
        pass

    def test_post_record_trace(self):
        """Test case for post_record_trace

        Record Trace  # noqa: E501
        """
        pass

    def test_post_trace_feedback(self):
        """Test case for post_trace_feedback

        Add Trace Feedback  # noqa: E501
        """
        pass

    def test_post_update(self):
        """Test case for post_update

        Update Completion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
