# coding: utf-8

"""
    Freeplay API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ObservabilityApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_delete_session(self, project_id, session_id, **kwargs):  # noqa: E501
        """Delete Session  # noqa: E501

         Permanently delete a session and all associated completions. Use when removing test data or honoring data deletion requests.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_delete_session(project_id, session_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_delete_session_with_http_info(project_id, session_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_delete_session_with_http_info(project_id, session_id, **kwargs)  # noqa: E501
            return data

    def delete_delete_session_with_http_info(self, project_id, session_id, **kwargs):  # noqa: E501
        """Delete Session  # noqa: E501

         Permanently delete a session and all associated completions. Use when removing test data or honoring data deletion requests.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_delete_session_with_http_info(project_id, session_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'session_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_delete_session" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `delete_delete_session`")  # noqa: E501
        # verify the required parameter 'session_id' is set
        if ('session_id' not in params or
                params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `delete_delete_session`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'session_id' in params:
            path_params['session_id'] = params['session_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/sessions/{session_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def patch_update_session_metadata(self, project_id, session_id, **kwargs):  # noqa: E501
        """Update Session Metadata  # noqa: E501

         Merge custom metadata into an existing session. Use to enrich sessions with post-hoc context like user ID or business metrics. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/sessions)  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_update_session_metadata(project_id, session_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.patch_update_session_metadata_with_http_info(project_id, session_id, **kwargs)  # noqa: E501
        else:
            (data) = self.patch_update_session_metadata_with_http_info(project_id, session_id, **kwargs)  # noqa: E501
            return data

    def patch_update_session_metadata_with_http_info(self, project_id, session_id, **kwargs):  # noqa: E501
        """Update Session Metadata  # noqa: E501

         Merge custom metadata into an existing session. Use to enrich sessions with post-hoc context like user ID or business metrics. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/sessions)  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_update_session_metadata_with_http_info(project_id, session_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'session_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patch_update_session_metadata" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `patch_update_session_metadata`")  # noqa: E501
        # verify the required parameter 'session_id' is set
        if ('session_id' not in params or
                params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `patch_update_session_metadata`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'session_id' in params:
            path_params['session_id'] = params['session_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/sessions/id/{session_id}/metadata', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SimpleResponseWithMessage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def patch_update_trace_by_id(self, project_id, session_id, trace_id, **kwargs):  # noqa: E501
        """Update Trace by ID  # noqa: E501

         Update a trace's metadata and/or feedback by its trace ID. This endpoint is a superset of the older metadata and feedback update endpoints.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_update_trace_by_id(project_id, session_id, trace_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object trace_id: (required)
        :param TraceUpdateRequest body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.patch_update_trace_by_id_with_http_info(project_id, session_id, trace_id, **kwargs)  # noqa: E501
        else:
            (data) = self.patch_update_trace_by_id_with_http_info(project_id, session_id, trace_id, **kwargs)  # noqa: E501
            return data

    def patch_update_trace_by_id_with_http_info(self, project_id, session_id, trace_id, **kwargs):  # noqa: E501
        """Update Trace by ID  # noqa: E501

         Update a trace's metadata and/or feedback by its trace ID. This endpoint is a superset of the older metadata and feedback update endpoints.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_update_trace_by_id_with_http_info(project_id, session_id, trace_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object trace_id: (required)
        :param TraceUpdateRequest body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'session_id', 'trace_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patch_update_trace_by_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `patch_update_trace_by_id`")  # noqa: E501
        # verify the required parameter 'session_id' is set
        if ('session_id' not in params or
                params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `patch_update_trace_by_id`")  # noqa: E501
        # verify the required parameter 'trace_id' is set
        if ('trace_id' not in params or
                params['trace_id'] is None):
            raise ValueError("Missing the required parameter `trace_id` when calling `patch_update_trace_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'session_id' in params:
            path_params['session_id'] = params['session_id']  # noqa: E501
        if 'trace_id' in params:
            path_params['trace_id'] = params['trace_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/sessions/{session_id}/traces/id/{trace_id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SimpleResponseWithMessage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def patch_update_trace_by_otel_span_id(self, project_id, session_id, otel_span_id_hex, **kwargs):  # noqa: E501
        """Update Trace by OTEL Span ID  # noqa: E501

         Update a trace's metadata and/or feedback by its OpenTelemetry span ID (hex string).  Note: OTEL spans are mapped to Freeplay Traces, so we use the OTEL span ID to identify Traces.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_update_trace_by_otel_span_id(project_id, session_id, otel_span_id_hex, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object otel_span_id_hex: (required)
        :param TraceUpdateRequest1 body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.patch_update_trace_by_otel_span_id_with_http_info(project_id, session_id, otel_span_id_hex, **kwargs)  # noqa: E501
        else:
            (data) = self.patch_update_trace_by_otel_span_id_with_http_info(project_id, session_id, otel_span_id_hex, **kwargs)  # noqa: E501
            return data

    def patch_update_trace_by_otel_span_id_with_http_info(self, project_id, session_id, otel_span_id_hex, **kwargs):  # noqa: E501
        """Update Trace by OTEL Span ID  # noqa: E501

         Update a trace's metadata and/or feedback by its OpenTelemetry span ID (hex string).  Note: OTEL spans are mapped to Freeplay Traces, so we use the OTEL span ID to identify Traces.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_update_trace_by_otel_span_id_with_http_info(project_id, session_id, otel_span_id_hex, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object otel_span_id_hex: (required)
        :param TraceUpdateRequest1 body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'session_id', 'otel_span_id_hex', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patch_update_trace_by_otel_span_id" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `patch_update_trace_by_otel_span_id`")  # noqa: E501
        # verify the required parameter 'session_id' is set
        if ('session_id' not in params or
                params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `patch_update_trace_by_otel_span_id`")  # noqa: E501
        # verify the required parameter 'otel_span_id_hex' is set
        if ('otel_span_id_hex' not in params or
                params['otel_span_id_hex'] is None):
            raise ValueError("Missing the required parameter `otel_span_id_hex` when calling `patch_update_trace_by_otel_span_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'session_id' in params:
            path_params['session_id'] = params['session_id']  # noqa: E501
        if 'otel_span_id_hex' in params:
            path_params['otel_span_id_hex'] = params['otel_span_id_hex']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/sessions/{session_id}/traces/otel-span-id/{otel_span_id_hex}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SimpleResponseWithMessage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def patch_update_trace_metadata(self, project_id, session_id, trace_id, **kwargs):  # noqa: E501
        """Update Trace Metadata  # noqa: E501

         Merge custom metadata into an existing trace. Use to enrich traces with post-hoc context.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_update_trace_metadata(project_id, session_id, trace_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object trace_id: (required)
        :param object body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.patch_update_trace_metadata_with_http_info(project_id, session_id, trace_id, **kwargs)  # noqa: E501
        else:
            (data) = self.patch_update_trace_metadata_with_http_info(project_id, session_id, trace_id, **kwargs)  # noqa: E501
            return data

    def patch_update_trace_metadata_with_http_info(self, project_id, session_id, trace_id, **kwargs):  # noqa: E501
        """Update Trace Metadata  # noqa: E501

         Merge custom metadata into an existing trace. Use to enrich traces with post-hoc context.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patch_update_trace_metadata_with_http_info(project_id, session_id, trace_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object trace_id: (required)
        :param object body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'session_id', 'trace_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patch_update_trace_metadata" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `patch_update_trace_metadata`")  # noqa: E501
        # verify the required parameter 'session_id' is set
        if ('session_id' not in params or
                params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `patch_update_trace_metadata`")  # noqa: E501
        # verify the required parameter 'trace_id' is set
        if ('trace_id' not in params or
                params['trace_id'] is None):
            raise ValueError("Missing the required parameter `trace_id` when calling `patch_update_trace_metadata`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'session_id' in params:
            path_params['session_id'] = params['session_id']  # noqa: E501
        if 'trace_id' in params:
            path_params['trace_id'] = params['trace_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/sessions/{session_id}/traces/id/{trace_id}/metadata', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SimpleResponseWithMessage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_create_completion_feedback(self, project_id, completion_id, **kwargs):  # noqa: E501
        """Add Completion Feedback  # noqa: E501

         Record end-user feedback on a completion. Use to capture thumbs up/down ratings or custom feedback attributes. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/customer-feedback)  The `freeplay_feedback` field must be \"positive\" or \"negative\". Additional custom fields are supported.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_create_completion_feedback(project_id, completion_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object completion_id: (required)
        :param object body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_create_completion_feedback_with_http_info(project_id, completion_id, **kwargs)  # noqa: E501
        else:
            (data) = self.post_create_completion_feedback_with_http_info(project_id, completion_id, **kwargs)  # noqa: E501
            return data

    def post_create_completion_feedback_with_http_info(self, project_id, completion_id, **kwargs):  # noqa: E501
        """Add Completion Feedback  # noqa: E501

         Record end-user feedback on a completion. Use to capture thumbs up/down ratings or custom feedback attributes. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/customer-feedback)  The `freeplay_feedback` field must be \"positive\" or \"negative\". Additional custom fields are supported.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_create_completion_feedback_with_http_info(project_id, completion_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object completion_id: (required)
        :param object body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'completion_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_create_completion_feedback" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `post_create_completion_feedback`")  # noqa: E501
        # verify the required parameter 'completion_id' is set
        if ('completion_id' not in params or
                params['completion_id'] is None):
            raise ValueError("Missing the required parameter `completion_id` when calling `post_create_completion_feedback`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'completion_id' in params:
            path_params['completion_id'] = params['completion_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/completion-feedback/id/{completion_id}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SimpleResponseWithMessage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_record_completion(self, project_id, session_id, **kwargs):  # noqa: E501
        """Record Completion  # noqa: E501

         Log an LLM completion with its prompt, response, and metadata. This is the primary endpoint for observability. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/recording-completions)  Sessions are created implicitly—just generate a session_id client-side (UUID v4). Optionally provide your own completion_id too to avoid waiting for Freeplay's response.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_record_completion(project_id, session_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param RecordPayload body:
        :return: RecordCompletionInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_record_completion_with_http_info(project_id, session_id, **kwargs)  # noqa: E501
        else:
            (data) = self.post_record_completion_with_http_info(project_id, session_id, **kwargs)  # noqa: E501
            return data

    def post_record_completion_with_http_info(self, project_id, session_id, **kwargs):  # noqa: E501
        """Record Completion  # noqa: E501

         Log an LLM completion with its prompt, response, and metadata. This is the primary endpoint for observability. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/recording-completions)  Sessions are created implicitly—just generate a session_id client-side (UUID v4). Optionally provide your own completion_id too to avoid waiting for Freeplay's response.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_record_completion_with_http_info(project_id, session_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param RecordPayload body:
        :return: RecordCompletionInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'session_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_record_completion" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `post_record_completion`")  # noqa: E501
        # verify the required parameter 'session_id' is set
        if ('session_id' not in params or
                params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `post_record_completion`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'session_id' in params:
            path_params['session_id'] = params['session_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/sessions/{session_id}/completions', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RecordCompletionInfo',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_record_trace(self, project_id, session_id, trace_id, **kwargs):  # noqa: E501
        """Record Trace  # noqa: E501

         Create or update a trace within a session. Use to group related completions in agent workflows. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/traces)  Generate the trace_id client-side (UUID v4) to avoid round-trip latency.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_record_trace(project_id, session_id, trace_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object trace_id: (required)
        :param TracePayload body:
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_record_trace_with_http_info(project_id, session_id, trace_id, **kwargs)  # noqa: E501
        else:
            (data) = self.post_record_trace_with_http_info(project_id, session_id, trace_id, **kwargs)  # noqa: E501
            return data

    def post_record_trace_with_http_info(self, project_id, session_id, trace_id, **kwargs):  # noqa: E501
        """Record Trace  # noqa: E501

         Create or update a trace within a session. Use to group related completions in agent workflows. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/traces)  Generate the trace_id client-side (UUID v4) to avoid round-trip latency.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_record_trace_with_http_info(project_id, session_id, trace_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object session_id: (required)
        :param object trace_id: (required)
        :param TracePayload body:
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'session_id', 'trace_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_record_trace" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `post_record_trace`")  # noqa: E501
        # verify the required parameter 'session_id' is set
        if ('session_id' not in params or
                params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `post_record_trace`")  # noqa: E501
        # verify the required parameter 'trace_id' is set
        if ('trace_id' not in params or
                params['trace_id'] is None):
            raise ValueError("Missing the required parameter `trace_id` when calling `post_record_trace`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'session_id' in params:
            path_params['session_id'] = params['session_id']  # noqa: E501
        if 'trace_id' in params:
            path_params['trace_id'] = params['trace_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/sessions/{session_id}/traces/id/{trace_id}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_trace_feedback(self, project_id, trace_id, **kwargs):  # noqa: E501
        """Add Trace Feedback  # noqa: E501

         Record end-user feedback on a trace. Use to capture feedback on conversation turns or agent workflow outcomes. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/customer-feedback)  The `freeplay_feedback` field must be \"positive\" or \"negative\". Additional custom fields are supported.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_trace_feedback(project_id, trace_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object trace_id: (required)
        :param object body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_trace_feedback_with_http_info(project_id, trace_id, **kwargs)  # noqa: E501
        else:
            (data) = self.post_trace_feedback_with_http_info(project_id, trace_id, **kwargs)  # noqa: E501
            return data

    def post_trace_feedback_with_http_info(self, project_id, trace_id, **kwargs):  # noqa: E501
        """Add Trace Feedback  # noqa: E501

         Record end-user feedback on a trace. Use to capture feedback on conversation turns or agent workflow outcomes. [See SDK method.](https://docs.freeplay.ai/freeplay-sdk/customer-feedback)  The `freeplay_feedback` field must be \"positive\" or \"negative\". Additional custom fields are supported.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_trace_feedback_with_http_info(project_id, trace_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object trace_id: (required)
        :param object body:
        :return: SimpleResponseWithMessage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'trace_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_trace_feedback" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `post_trace_feedback`")  # noqa: E501
        # verify the required parameter 'trace_id' is set
        if ('trace_id' not in params or
                params['trace_id'] is None):
            raise ValueError("Missing the required parameter `trace_id` when calling `post_trace_feedback`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'trace_id' in params:
            path_params['trace_id'] = params['trace_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/trace-feedback/id/{trace_id}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SimpleResponseWithMessage',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_update(self, project_id, completion_id, **kwargs):  # noqa: E501
        """Update Completion  # noqa: E501

         Append messages or evaluation results to an existing completion. Use for streaming responses or adding post-hoc evaluation metrics.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_update(project_id, completion_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object completion_id: (required)
        :param RecordUpdatePayload body:
        :return: RecordCompletionInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_update_with_http_info(project_id, completion_id, **kwargs)  # noqa: E501
        else:
            (data) = self.post_update_with_http_info(project_id, completion_id, **kwargs)  # noqa: E501
            return data

    def post_update_with_http_info(self, project_id, completion_id, **kwargs):  # noqa: E501
        """Update Completion  # noqa: E501

         Append messages or evaluation results to an existing completion. Use for streaming responses or adding post-hoc evaluation metrics.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_update_with_http_info(project_id, completion_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object project_id: (required)
        :param object completion_id: (required)
        :param RecordUpdatePayload body:
        :return: RecordCompletionInfo
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'completion_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `post_update`")  # noqa: E501
        # verify the required parameter 'completion_id' is set
        if ('completion_id' not in params or
                params['completion_id'] is None):
            raise ValueError("Missing the required parameter `completion_id` when calling `post_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'completion_id' in params:
            path_params['completion_id'] = params['completion_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerAuth']  # noqa: E501

        return self.api_client.call_api(
            '/api/v2/projects/{project_id}/completions/{completion_id}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='RecordCompletionInfo',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
